/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 player.gltf
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Player(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/assets/player.gltf');
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Scene'>
				<group
					name='Player'
					position={[0, 0, 0]}
					rotation={[Math.PI, -0.63, Math.PI]}
					mass={10}
				>
					<group name='root' rotation={[-1.57, 0, 0]}>
						<group
							name='torso'
							position={[-0.01, 0.08, 0.15]}
							rotation={[3, 0, 0]}
						>
							<group
								name='thighBL'
								position={[0.05, 0.02, 0.05]}
								rotation={[1.5, 0.04, -0.08]}
							>
								<group
									name='legupperBL'
									position={[0, 0.05, 0]}
									rotation={[0.91, 0.02, 0.09]}
								>
									<group
										name='leglowerBL'
										position={[0, 0.04, 0]}
										rotation={[-0.94, 0, 0.02]}
									>
										<group
											name='footBL'
											position={[0, 0.05, 0]}
											rotation={[-1.22, 0.02, 0.02]}
										/>
									</group>
								</group>
							</group>
							<group
								name='tail'
								position={[0, -0.01, 0]}
								rotation={[-2.83, -0.02, 0.15]}
							>
								<group
									name='tail01'
									position={[0, 0.05, 0]}
									rotation={[0.46, 0.02, 0.04]}
								>
									<group
										name='tail02'
										position={[0, 0.04, 0]}
										rotation={[0.42, -0.01, 0.09]}
									>
										<group
											name='tail03'
											position={[0, 0.05, 0]}
											rotation={[0.48, -0.01, 0.09]}
										>
											<group
												name='tailend'
												position={[0, 0.04, 0]}
												rotation={[0.54, -0.01, 0.09]}
											/>
										</group>
									</group>
								</group>
							</group>
							<group
								name='spine01'
								position={[0, 0.07, 0]}
								rotation={[0.17, 0, 0]}
							>
								<group
									name='spine02'
									position={[0, 0.07, 0]}
									rotation={[-0.11, 0, 0]}
								>
									<group
										name='legupperFL'
										position={[0.04, 0.11, 0.21]}
										rotation={[1.35, -0.02, -0.01]}
									>
										<group
											name='leglowerFL'
											position={[0, 0.07, 0]}
											rotation={[-0.5, -0.02, 0.05]}
										>
											<group
												name='footFL'
												position={[0, 0.05, 0]}
												rotation={[-0.55, 0.04, -0.01]}
											/>
										</group>
									</group>
									<group
										name='neck'
										position={[0, 0.05, 0]}
										rotation={[-0.69, 0, 0]}
									>
										<group
											name='head'
											position={[0, 0.03, 0]}
											rotation={[-0.33, 0.01, 0.03]}
										>
											<group
												name='earL'
												position={[0.05, 0.1, -0.01]}
												rotation={[-0.12, 0.83, -0.36]}
											/>
											<group
												name='earR'
												position={[-0.05, 0.1, -0.01]}
												rotation={[-0.13, -0.83, 0.36]}
											/>
											<group
												name='mouth'
												position={[0, 0.03, 0.07]}
												rotation={[1.24, 0, 0]}
											/>
											<group
												name='eyeL'
												position={[0.04, 0.07, 0.06]}
												rotation={[-0.43, 0, 0.07]}
											/>
											<group
												name='eyeR'
												position={[-0.04, 0.07, 0.06]}
												rotation={[-0.43, 0, -0.07]}
											/>
										</group>
									</group>
									<group
										name='legupperFR'
										position={[-0.04, -0.16, 0.16]}
										rotation={[2.28, 0, 0.01]}
									>
										<group
											name='leglowerFR'
											position={[0, 0.07, 0]}
											rotation={[-0.37, -0.02, -0.09]}
										>
											<group
												name='footFR'
												position={[0, 0.05, 0]}
												rotation={[-1.62, -0.08, 0.02]}
											/>
										</group>
									</group>
								</group>
							</group>
							<group
								name='thighBR'
								position={[-0.05, -0.07, 0.04]}
								rotation={[1.84, -0.04, 0.09]}
							>
								<group
									name='legupperBR'
									position={[0, 0.05, 0]}
									rotation={[1.37, -0.07, -0.08]}
								>
									<group
										name='leglowerBR'
										position={[0, 0.04, 0]}
										rotation={[-0.81, 0, -0.03]}
									>
										<group
											name='footBR'
											position={[0, 0.05, 0]}
											rotation={[-0.36, -0.04, 0.03]}
										/>
									</group>
								</group>
							</group>
							<group
								name='tailCTRL'
								position={[0, -0.02, -0.04]}
								rotation={[-2.53, -0.01, 0.09]}
							/>
						</group>
						<group
							name='footFIKL'
							position={[0.04, -0.66, 0.01]}
							rotation={[-2.93, 0, 0]}
						/>
						<group
							name='footBIKL'
							position={[0.05, -0.06, 0.01]}
							rotation={[-3.05, 0, 0]}
						/>
						<group
							name='footFIKR'
							position={[-0.04, 0.72, 0.01]}
							rotation={[-2.93, 0, 0]}
						/>
						<group
							name='footBIKR'
							position={[-0.05, 0.79, 0.37]}
							rotation={[-1.25, 0, 0]}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/assets/player.gltf');
