// eslint-disable-next-line
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 room_alpha.gltf
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props: any) {
	const { nodes, materials } = useGLTF('/assets/room_alpha.gltf');
	return (
		<group {...props} dispose={null}>
			<group
				position={[1.88, 1.97, -1.33]}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
			>
				<group position={[0, 0.22, -0.37]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.MH1.geometry}
						material={materials.Material_0}
						position={[-0.02, 0, 0.89]}
						rotation={[Math.PI, -1.31, Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.MH2.geometry}
						material={materials.Material_0}
						position={[-0.01, 0, 0.84]}
						rotation={[0, -0.44, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.MH3.geometry}
						material={materials.Material_0}
						position={[0, 0, 0.79]}
						rotation={[0, Math.PI / 8, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.MH4.geometry}
						material={materials.Material_0}
						position={[0.01, 0, 0.75]}
						rotation={[0, -0.7, 0]}
					/>
				</group>
				<group position={[0, 0.22, -0.37]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.cylinder.geometry}
						material={materials.Material_0}
						position={[0.01, 0, 0.75]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.String1.geometry}
						material={materials.Material_0}
						position={[0, -0.22, 0.37]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.String2.geometry}
						material={materials.Material_0}
						position={[0, -0.22, 0.37]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.String3.geometry}
						material={materials.Material_0}
						position={[0, -0.22, 0.37]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.String4.geometry}
						material={materials.Material_0}
						position={[0, 0.01, 0.72]}
					/>
				</group>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Body.geometry}
					material={materials.Material_0}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Bridge.geometry}
					material={materials.Material_0}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.cube.geometry}
					material={materials.Material_0}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Frets.geometry}
					material={materials.Material_0}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Input.geometry}
					material={materials.Material_0}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes['Neck&Head'].geometry}
					material={materials.Material_0}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Nobs1.geometry}
					material={materials.Material_0}
					position={[-0.1, 0, -0.42]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Nobs2.geometry}
					material={materials.Material_0}
					position={[-0.12, 0, -0.45]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Nobs3.geometry}
					material={materials.Material_0}
					position={[-0.14, 0, -0.48]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.PickGuard.geometry}
					material={materials.Material_0}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.PickUps.geometry}
					material={materials.Material_0}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.StrapPin1.geometry}
					material={materials.Material_0}
					position={[-0.02, 0, -0.6]}
					rotation={[0, -0.13, 0]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.StrapPin2.geometry}
					material={materials.Material_0}
					position={[0.08, 0.14, -0.1]}
					rotation={[-Math.PI, Math.PI / 8, -Math.PI]}
				/>
			</group>
			<group
				position={[-0.65, 0.4, 1.55]}
				rotation={[Math.PI / 2, 0, -Math.PI / 3]}
			>
				<group rotation={[0, 0, Math.PI / 6]}>
					<group rotation={[0, 0, Math.PI / 6]}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.r0005.geometry}
							material={materials.Phong_FFFFFF}
							position={[0, 0, -0.19]}
							rotation={[-Math.PI / 2, Math.PI / 3, 0]}
							scale={[0.92, 1, 0.92]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.r0006.geometry}
							material={materials.Standard_68522A}
							position={[0, 0, -0.39]}
							rotation={[-Math.PI / 2, Math.PI / 3, 0]}
							scale={[0.84, 1, 0.84]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0014.geometry}
							material={materials.Phong_3D8344}
							position={[0.42, 0.08, -1]}
							rotation={[-0.55, 0.19, -1.31]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0016.geometry}
							material={materials.Phong_3D8344}
							position={[0.03, 0.06, -0.71]}
							rotation={[0, 0, -0.33]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0017.geometry}
							material={materials.Phong_3D8344}
							position={[0.15, -0.23, -0.48]}
							rotation={[-0.02, 0.29, -2.42]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0018.geometry}
							material={materials.Phong_3D8344}
							position={[0.3, -0.01, -0.67]}
							rotation={[-0.15, 0.43, -1.08]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0019.geometry}
							material={materials.Phong_3D8344}
							position={[0.2, 0.17, -0.8]}
							rotation={[-0.73, 0.07, -0.23]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0020.geometry}
							material={materials.Phong_3D8344}
							position={[-0.09, 0.26, -0.86]}
							rotation={[-0.31, -0.44, 0.88]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0021.geometry}
							material={materials.Phong_3D8344}
							position={[0.19, -0.09, -0.88]}
							rotation={[-0.46, 0.49, -1.71]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0022.geometry}
							material={materials.Phong_3D8344}
							position={[0.03, 0.37, -0.94]}
							rotation={[-0.29, -0.16, 0.78]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0023.geometry}
							material={materials.Phong_3D8344}
							position={[-0.13, -0.14, -0.42]}
							rotation={[0.43, -0.04, 2.9]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0024.geometry}
							material={materials.Phong_3D8344}
							position={[-0.02, 0.21, -0.41]}
							rotation={[0.06, -0.34, 0.75]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0025.geometry}
							material={materials.Phong_3D8344}
							position={[0.22, 0.08, -0.48]}
							rotation={[-0.42, 0.17, -0.62]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0026.geometry}
							material={materials.Phong_3D8344}
							position={[-0.08, 0.16, -0.64]}
							rotation={[-0.09, -0.71, 1.18]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0027.geometry}
							material={materials.Phong_3D8344}
							position={[-0.03, -0.16, -0.59]}
							rotation={[0.24, 0.25, 3.09]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0028.geometry}
							material={materials.Phong_3D8344}
							position={[0.16, -0.2, -0.73]}
							rotation={[-0.2, 0.04, -2.22]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0030.geometry}
							material={materials.Phong_3D8344}
							position={[-0.18, 0.04, -0.61]}
							rotation={[0.04, 0.01, 2.3]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0047.geometry}
							material={materials.Phong_3D8344}
							position={[-0.22, 0.08, -0.82]}
							rotation={[0.12, -0.24, 2.01]}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.s0050.geometry}
							material={materials.Phong_3D8344}
							position={[-0.07, -0.09, -0.91]}
							rotation={[0.38, 0.19, 2.88]}
						/>
					</group>
				</group>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane.geometry}
				material={materials['Material.015']}
				position={[4.57, 0, 11.28]}
				rotation={[-Math.PI, 0, -Math.PI]}
				scale={1.04}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube106.geometry}
				material={materials['Metal Black']}
				position={[1.9, 2.42, -1.25]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube135.geometry}
				material={materials['Shiny Metal.Window']}
				position={[0.8, 2.5, -1.57]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube115.geometry}
				material={materials['Glass.007']}
				position={[0.8, 2.56, -1.64]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube116.geometry}
				material={materials['Metal Black']}
				position={[0.8, 2.45, -1.58]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube117.geometry}
				material={materials['Glass.007']}
				position={[0.8, 2.07, -1.58]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube141.geometry}
				material={materials['Metal Black.003']}
				position={[0.8, 2.08, -1.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube103.geometry}
				material={materials['Metal Black.001']}
				position={[0.8, 2.13, -1.64]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube104.geometry}
				material={materials['Metal Black.004']}
				position={[0.8, 1.66, -1.58]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Floor.geometry}
				material={materials.Floor}
				position={[3.32, 0.19, 0.86]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Right_Wall.geometry}
				material={materials.Wall}
				position={[4.4, 1.83, -1.31]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Left_Wall.geometry}
				material={materials.Wall}
				position={[-1.43, 1.83, 0.86]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Keyboard_Frame.geometry}
				material={materials['Keyboard Base']}
				position={[-0.09, 1.24, -0.11]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube015.geometry}
				material={materials['Keyboard Base']}
				position={[-0.13, 1.26, 0.04]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube016.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.13, 1.26, 0]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube017.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.13, 1.26, -0.02]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube018.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.13, 1.26, -0.06]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube019.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.13, 1.26, -0.04]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube024.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.13, 1.26, -0.2]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube025.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.13, 1.26, -0.22]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube026.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.13, 1.26, -0.18]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube027.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.13, 1.26, -0.16]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube030.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, 0.04]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube014.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, 0]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube031.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, 0.02]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube032.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, -0.04]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube033.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, -0.02]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube034.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, -0.06]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube035.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, -0.12]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube036.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, -0.08]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube037.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, -0.1]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube038.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, -0.16]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube039.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, -0.14]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube040.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, -0.18]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube041.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.11, 1.25, -0.2]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube044.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, -0.24]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube045.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, -0.21]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube046.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, -0.17]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube047.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, -0.19]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube048.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, -0.13]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube049.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, -0.11]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube050.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, -0.15]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube051.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, -0.09]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube052.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, -0.05]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube053.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, -0.07]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube054.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, -0.01]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube055.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, 0.01]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube056.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.08, 1.25, -0.03]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube061.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.06, 1.25, -0.04]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube062.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.06, 1.25, 0]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube063.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.06, 1.25, -0.02]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube064.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.06, 1.25, -0.08]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube065.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.06, 1.25, -0.06]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube066.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.06, 1.25, -0.09]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube067.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.06, 1.25, -0.15]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube068.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.06, 1.25, -0.11]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube069.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.06, 1.25, -0.13]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube070.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.06, 1.25, -0.19]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube071.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.06, 1.25, -0.17]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube076.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.04, 1.25, -0.19]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube078.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.04, 1.25, -0.15]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube079.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.04, 1.25, -0.13]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube080.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.04, 1.25, -0.17]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube081.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.04, 1.25, -0.11]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube082.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.04, 1.25, -0.07]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube083.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.04, 1.25, -0.09]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube084.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.04, 1.25, -0.03]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube085.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.04, 1.25, -0.01]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube086.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.04, 1.25, -0.05]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube091.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.02, 1.25, 0]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube093.geometry}
				material={materials['Keyboard Variant 2']}
				position={[-0.02, 1.25, 0.02]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube020.geometry}
				material={materials['Keyboard Base']}
				position={[-0.13, 1.26, -0.12]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube021.geometry}
				material={materials['Keyboard Base']}
				position={[-0.13, 1.26, -0.14]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube022.geometry}
				material={materials['Keyboard Base']}
				position={[-0.13, 1.26, -0.1]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube023.geometry}
				material={materials['Keyboard Base']}
				position={[-0.13, 1.26, -0.08]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube028.geometry}
				material={materials['Keyboard Base']}
				position={[-0.13, 1.26, -0.24]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube029.geometry}
				material={materials['Keyboard Base']}
				position={[-0.13, 1.26, -0.26]}
				rotation={[0, 0, -0.61]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube042.geometry}
				material={materials['Keyboard Variant 1']}
				position={[-0.11, 1.25, -0.26]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube043.geometry}
				material={materials['Keyboard Base']}
				position={[-0.11, 1.25, -0.23]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube057.geometry}
				material={materials['Keyboard Base']}
				position={[-0.08, 1.25, 0.04]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube058.geometry}
				material={materials['Keyboard Variant 1']}
				position={[-0.08, 1.25, -0.26]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube059.geometry}
				material={materials['Keyboard Variant 1']}
				position={[-0.06, 1.25, -0.26]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube060.geometry}
				material={materials['Keyboard Base']}
				position={[-0.06, 1.25, 0.03]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube073.geometry}
				material={materials['Keyboard Base']}
				position={[-0.06, 1.25, -0.23]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube074.geometry}
				material={materials['Keyboard Base']}
				position={[-0.04, 1.25, -0.21]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube075.geometry}
				material={materials['Keyboard Base']}
				position={[-0.04, 1.25, -0.24]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube087.geometry}
				material={materials['Keyboard Base']}
				position={[-0.04, 1.25, 0.03]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube088.geometry}
				material={materials['Keyboard Variant 1']}
				position={[-0.04, 1.25, -0.26]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube092.geometry}
				material={materials['Keyboard Base']}
				position={[-0.02, 1.25, 0.04]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube097.geometry}
				material={materials['Keyboard Base']}
				position={[-0.02, 1.25, -0.2]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube098.geometry}
				material={materials['Keyboard Base']}
				position={[-0.02, 1.25, -0.16]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube099.geometry}
				material={materials['Keyboard Base']}
				position={[-0.02, 1.25, -0.18]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube100.geometry}
				material={materials['Keyboard Base']}
				position={[-0.02, 1.25, -0.24]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube101.geometry}
				material={materials['Keyboard Base']}
				position={[-0.02, 1.25, -0.22]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube102.geometry}
				material={materials['Keyboard Base']}
				position={[-0.02, 1.25, -0.26]}
				rotation={[0, 0, -0.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube089.geometry}
				material={materials['Keyboard Variant 1']}
				position={[-0.02, 1.24, -0.08]}
				rotation={[0, 0, -0.11]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Table_Top.geometry}
				material={materials['Wood Black']}
				position={[-0.7, 1.33, -0.09]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder003.geometry}
				material={materials.Material}
				position={[-0.7, 0.7, 0.89]}
				rotation={[0.07, 0.07, -0.78]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder001.geometry}
				material={materials['Material.001']}
				position={[-0.7, 0.7, -1.05]}
				rotation={[0.07, 0.07, -0.78]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube005.geometry}
				material={materials['Wood Black']}
				position={[-0.13, 1.2, -0.08]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube012.geometry}
				material={materials['Metal Black']}
				position={[-0.5, 1.21, 0.47]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube009.geometry}
				material={materials['Metal Black']}
				position={[-0.5, 1.21, -0.64]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube118.geometry}
				material={materials['Metal Black']}
				position={[-0.13, 1.2, 0.46]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube119.geometry}
				material={materials['Metal Black']}
				position={[-0.13, 1.2, -0.64]}
			/>
			<group
				position={[0.7, 0.56, -0.61]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Mesh.geometry}
					material={materials.Matteplastic}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Mesh_1.geometry}
					material={materials.BlackMetal}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rectangle11.geometry}
				material={materials.BlackMetal}
				position={[0.67, 0.92, -0.54]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Line01.geometry}
				material={materials.BlackMetal}
				position={[0.71, 0.84, -0.65]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder03.geometry}
				material={materials.Matteplastic}
				position={[0.67, 0.84, -0.52]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Line02.geometry}
				material={materials.BlackMetal}
				position={[0.45, 0.84, -0.75]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle01.geometry}
				material={materials.Matteplastic}
				position={[0.4, 0.85, -0.81]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder07.geometry}
				material={materials.BlackMetal}
				position={[0.91, 0.88, -0.5]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder08.geometry}
				material={materials.BlackMetal}
				position={[0.88, 0.88, -0.42]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder09.geometry}
				material={materials.BlackMetal}
				position={[0.95, 0.89, -0.4]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder10.geometry}
				material={materials.BlackMetal}
				position={[0.97, 0.89, -0.48]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder11.geometry}
				material={materials.BlackMetal}
				position={[0.4, 0.89, -0.67]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder12.geometry}
				material={materials.BlackMetal}
				position={[0.46, 0.88, -0.65]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder13.geometry}
				material={materials.BlackMetal}
				position={[0.37, 0.89, -0.6]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder14.geometry}
				material={materials.BlackMetal}
				position={[0.44, 0.88, -0.58]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Line04.geometry}
				material={materials.Matteplastic}
				position={[0.33, 1.16, -0.69]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder15.geometry}
				material={materials.BlackMetal}
				position={[0.34, 0.96, -0.71]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder16.geometry}
				material={materials.BlackMetal}
				position={[0.31, 0.97, -0.62]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Line05.geometry}
				material={materials.Matteplastic}
				position={[1.03, 1.16, -0.45]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder17.geometry}
				material={materials.BlackMetal}
				position={[1.01, 0.97, -0.38]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder18.geometry}
				material={materials.BlackMetal}
				position={[1.04, 0.96, -0.47]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Box01.geometry}
				material={materials.Lether}
				position={[0.57, 0.97, -0.25]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			/>
			<group
				position={[1.14, 1.24, -0.86]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Mesh022.geometry}
					material={materials.Lether}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Mesh022_1.geometry}
					material={materials.Chairback}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rectangle02.geometry}
				material={materials.Chrome}
				position={[0.7, 0.53, -0.61]}
				rotation={[-Math.PI, -1.24, -Math.PI]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder04.geometry}
					material={materials.Matteplastic}
					position={[-0.13, -0.05, -0.37]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder02.geometry}
						material={materials.Matteplastic}
						position={[-0.02, -0.06, 0]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder20.geometry}
					material={materials.Matteplastic}
					position={[0.31, -0.05, -0.23]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder19.geometry}
						material={materials.Matteplastic}
						position={[-0.01, -0.06, -0.02]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder21.geometry}
					material={materials.Matteplastic}
					position={[0.32, -0.05, 0.22]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder22.geometry}
						material={materials.Matteplastic}
						position={[0.01, -0.06, -0.02]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder23.geometry}
					material={materials.Matteplastic}
					position={[-0.11, -0.05, 0.37]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder24.geometry}
						material={materials.Matteplastic}
						position={[0.02, -0.06, 0]}
					/>
				</mesh>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder26.geometry}
					material={materials.Matteplastic}
					position={[-0.39, -0.05, 0.01]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder25.geometry}
						material={materials.Matteplastic}
						position={[-0.01, -0.06, -0.02]}
					/>
				</mesh>
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Bedframe.geometry}
				material={materials['Wood Black']}
				position={[4.53, 0.47, 0.18]}
				rotation={[0, 1.57, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane007.geometry}
				material={materials['Material.010']}
				position={[4.53, 1.31, 0.42]}
				rotation={[-Math.PI, -0.76, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane006.geometry}
				material={materials['Material.010']}
				position={[4.53, 0.66, 0.16]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane003.geometry}
				material={materials['Material.010']}
				position={[4.47, 1.23, -0.62]}
				rotation={[-0.06, -0.26, 0.62]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane005.geometry}
				material={materials['Material.010']}
				position={[4.54, 1.23, -0.4]}
				rotation={[0.05, -0.98, -0.24]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube001.geometry}
				material={materials['Wood Black']}
				position={[4.53, 0.69, -1.21]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube002.geometry}
				material={materials['Wood Black']}
				position={[4.53, 0.96, -1.21]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube003.geometry}
				material={materials['Wood Black']}
				position={[4.53, 1.23, -1.21]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube004.geometry}
				material={materials['Wood Black']}
				position={[4.53, 1.5, -1.21]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane004.geometry}
				material={materials['Metal Black']}
				position={[3.31, 0.67, -0.97]}
				rotation={[0, 1.57, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane011.geometry}
				material={materials['Metal Black']}
				position={[5.72, 0.67, -0.97]}
				rotation={[0, 1.57, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane012.geometry}
				material={materials['Metal Black']}
				position={[3.32, 1.21, -0.99]}
				rotation={[0, 1.57, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane013.geometry}
				material={materials['Metal Black']}
				position={[5.73, 1.21, -0.99]}
				rotation={[0, 1.57, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube121.geometry}
				material={materials['Metal Black']}
				position={[-0.9, 1.38, 0.85]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube122.geometry}
				material={materials['Rubber Black']}
				position={[-0.9, 1.46, 0.68]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube123.geometry}
				material={materials['Metal Black']}
				position={[-0.91, 1.63, 0.85]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube124.geometry}
				material={materials['Metal Black']}
				position={[-0.91, 1.63, 0.51]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube125.geometry}
				material={materials['Metal Black']}
				position={[-0.9, 1.38, 0.52]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube126.geometry}
				material={materials['Metal Black']}
				position={[-0.82, 1.43, 0.69]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube127.geometry}
				material={materials['Metal Black']}
				position={[-0.88, 1.55, 0.68]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube128.geometry}
				material={materials['Metal Black']}
				position={[-0.91, 1.89, 0.68]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube129.geometry}
				material={materials['Metal Black']}
				position={[-0.91, 1.95, 0.76]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder007.geometry}
				material={materials['Rubber Black']}
				position={[-0.96, 2, 0.76]}
				rotation={[0, 0, -Math.PI / 2]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder008.geometry}
				material={materials['Rubber Black']}
				position={[-0.93, 2, 0.76]}
				rotation={[0, 0, -Math.PI / 2]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder009.geometry}
				material={materials['Rubber Black']}
				position={[-0.98, 2, 0.76]}
				rotation={[0, 0, -Math.PI / 2]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder010.geometry}
				material={materials['Rubber Black']}
				position={[-1.02, 2, 0.76]}
				rotation={[0, 0, -Math.PI / 2]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube130.geometry}
				material={materials['Metal Black']}
				position={[-0.73, 1.41, 0.51]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube132.geometry}
				material={materials['Glass.001']}
				position={[-0.75, 1.44, 0.51]}
				rotation={[0, 0, 0.96]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder011.geometry}
				material={materials['Metal Black']}
				position={[-0.72, 1.42, 0.49]}
				rotation={[0, 0, -Math.PI / 5]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube006.geometry}
				material={materials['Metal Black']}
				position={[-0.83, 1.47, -0.92]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube120.geometry}
				material={materials['Glass.007']}
				position={[-0.83, 1.68, -0.8]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube.geometry}
				material={materials['Rubber Black']}
				position={[-0.91, 1.61, -0.93]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube072.geometry}
				material={materials['Material.002']}
				position={[-0.97, 1.59, -0.85]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube077.geometry}
				material={materials.Mat_Gradient}
				position={[-0.91, 1.59, -0.85]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder002.geometry}
				material={materials['Plastic Light']}
				position={[-0.66, 1.87, -1.01]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder004.geometry}
				material={materials['Rubber Black']}
				position={[-0.93, 1.73, -1.01]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder005.geometry}
				material={materials['Material.003']}
				position={[-0.93, 1.73, -0.99]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder006.geometry}
				material={materials['Material.004']}
				position={[-0.93, 1.73, -0.99]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder012.geometry}
				material={materials['Table Lamp']}
				position={[-0.41, 1.33, 0.98]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder013.geometry}
				material={materials['Table Lamp']}
				position={[-0.41, 1.71, 0.87]}
				rotation={[-0.34, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder014.geometry}
				material={materials['Table Lamp']}
				position={[-0.41, 2.1, 0.5]}
				rotation={[-1.27, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube131.geometry}
				material={materials['Table Lamp']}
				position={[-0.41, 2.2, 0.03]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube133.geometry}
				material={materials['Material.007']}
				position={[-0.41, 2.19, -0.05]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder015.geometry}
				material={materials['Table Lamp']}
				position={[-0.41, 2.19, 0.25]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder019.geometry}
				material={materials['Metal Black.007']}
				position={[-0.68, 1.52, -0.64]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder020.geometry}
				material={materials['Table Lamp']}
				position={[-0.68, 1.63, -0.64]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder.geometry}
				material={materials['Table Lamp']}
				position={[-0.41, 1.39, 0.98]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder018.geometry}
				material={materials['Table Lamp']}
				position={[-0.41, 2.01, 0.76]}
				rotation={[0, 0, -Math.PI / 2]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube008.geometry}
				material={materials['Material.009']}
				position={[-0.83, 1.69, -0.08]}
				scale={[1, 0.96, 0.98]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube134.geometry}
				material={materials['Metal Black']}
				position={[-0.89, 1.69, -0.09]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube108.geometry}
				material={materials['Rubber Black']}
				position={[-0.87, 1.69, -0.08]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube010.geometry}
				material={materials['Rubber Black']}
				position={[-0.95, 1.6, -0.09]}
				rotation={[Math.PI, 0, -2.88]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube011.geometry}
				material={materials['Rubber Black']}
				position={[-0.94, 1.38, -0.09]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane008.geometry}
				material={materials['Metal Black Phone']}
				position={[-0.4, 1.37, -0.49]}
				rotation={[0, -0.41, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane010.geometry}
				material={materials['Material.008']}
				position={[-0.4, 1.38, -0.49]}
				scale={0.98}
			/>
			<group position={[-0.88, 1.41, -0.09]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Sphere004.geometry}
					material={materials['Material.008']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Sphere004_1.geometry}
					material={materials['Rubber Black']}
				/>
			</group>
			<group position={[-0.89, 0.31, 2.37]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane018_1.geometry}
					material={materials['Glass.003']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane018_2.geometry}
					material={materials['Metal Black']}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube007.geometry}
				material={materials['Rubber Black']}
				position={[-0.52, 1.36, -0.09]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube096.geometry}
				material={materials['Material.019']}
				position={[-1.23, 2.19, 1.71]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane001.geometry}
				material={materials['Wood Black']}
				position={[-1.27, 2.19, 1.71]}
				rotation={[0, 0, -Math.PI / 2]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube090.geometry}
				material={materials['Material.011']}
				position={[-1.23, 1.81, 2.49]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane002.geometry}
				material={materials['Wood Black']}
				position={[-1.27, 1.81, 2.49]}
				rotation={[0, 0, -Math.PI / 2]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube094.geometry}
				material={materials['Bed Painting']}
				position={[4.53, 2.41, -1.21]}
				rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube095.geometry}
				material={materials['Wood Black']}
				position={[4.53, 2.41, -1.23]}
				rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Sphere005.geometry}
				material={materials['Glass Bulb.001']}
				position={[2.93, 2.1, -0.81]}
				rotation={[-2.3, 0.85, 2.74]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Sphere006.geometry}
				material={materials['Glass Bulb.001']}
				position={[2.93, 2.1, -0.81]}
				rotation={[-2.3, 0.85, 2.74]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Sphere007.geometry}
				material={materials['Plastic Light Cover.001']}
				position={[3.01, 2.02, -0.78]}
				rotation={[0.84, -0.85, -0.24]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder016.geometry}
				material={nodes.Cylinder016.material}
				position={[2.83, 0.42, -0.83]}
				rotation={[-Math.PI, 1.38, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder017.geometry}
				material={nodes.Cylinder017.material}
				position={[2.83, 1.54, -0.83]}
				rotation={[-Math.PI, 1.38, -Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Sphere002.geometry}
				material={materials['Plastic Light Cover.002']}
				position={[2.91, 2.47, -0.66]}
				rotation={[1.32, -1.04, 0.34]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Sphere003.geometry}
				material={materials['Glass Bulb.002']}
				position={[2.85, 2.55, -0.72]}
				rotation={[-1.82, 1.04, 2.16]}
			/>
			<group position={[1.96, 0.78, 2.36]} rotation={[-0.36, 0.75, 0.25]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube028_1.geometry}
					material={materials['Material.017']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube028_2.geometry}
					material={materials['Material.018']}
				/>
			</group>
			<group position={[1.87, 1.21, 2.28]} rotation={[-0.36, 0.75, 0.25]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube030_1.geometry}
					material={materials['Material.017']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube030_2.geometry}
					material={materials['Material.018']}
				/>
			</group>
			<group
				position={[1.68, 0.77, 2.08]}
				rotation={[0.36, 0.75, -0.25]}
				scale={[1, -1, 1]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube046_1.geometry}
					material={materials['Material.020']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube046_2.geometry}
					material={materials['Material.021']}
				/>
			</group>
			<group
				position={[1.76, 1.2, 2.17]}
				rotation={[0.36, 0.75, -0.25]}
				scale={[1, -1, 1]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube047_1.geometry}
					material={materials['Material.020']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube047_2.geometry}
					material={materials['Material.021']}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube148.geometry}
				material={materials['Material.012']}
				position={[4.53, 0.4, 0.46]}
				rotation={[0, 1.57, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube013.geometry}
				material={materials['Wood Black']}
				position={[2.75, 1.23, 0.59]}
			/>
			<group position={[2.75, 0.63, -0.09]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube024_1.geometry}
					material={materials['Bookshelf Inset']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube024_2.geometry}
					material={materials.Nob}
				/>
			</group>
			<group position={[2.75, 0.63, 1.27]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube023_1.geometry}
					material={materials['Bookshelf Inset']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube023_2.geometry}
					material={materials.Nob}
				/>
			</group>
			<group position={[2.8, 0.55, 0.53]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane041_1.geometry}
					material={materials['Paper.025']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane041_2.geometry}
					material={materials['Book.025']}
				/>
			</group>
			<group position={[2.81, 0.58, 0.41]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane042_1.geometry}
					material={materials['Paper.026']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane042_2.geometry}
					material={materials['Book.026']}
				/>
			</group>
			<group position={[2.79, 0.58, 0.36]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane043_1.geometry}
					material={materials['Paper.027']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane043_2.geometry}
					material={materials['Book.027']}
				/>
			</group>
			<group
				position={[2.79, 0.61, 0.2]}
				rotation={[-0.17, -0.04, -0.03]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane044_1.geometry}
					material={materials['Paper.028']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane044_2.geometry}
					material={materials['Book.028']}
				/>
			</group>
			<group position={[2.81, 0.57, 0.3]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane045_1.geometry}
					material={materials['Paper.029']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane045_2.geometry}
					material={materials['Book.029']}
				/>
			</group>
			<group position={[2.77, 0.59, 0.47]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane040_1.geometry}
					material={materials['Paper.024']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane040_2.geometry}
					material={materials['Book.024']}
				/>
			</group>
			<group position={[2.75, 1.03, 0.81]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube025_1.geometry}
					material={materials['Bookshelf Inset']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube025_2.geometry}
					material={materials.Nob}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube025_3.geometry}
					material={materials['Chrome.005']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube025_4.geometry}
					material={materials['Chrome.006']}
				/>
			</group>
			<group position={[2.75, 1.03, 0.36]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube027_1.geometry}
					material={materials['Bookshelf Inset']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube027_2.geometry}
					material={materials.Nob}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube027_3.geometry}
					material={materials['Chrome.005']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube027_4.geometry}
					material={materials['Chrome.006']}
				/>
			</group>
			<group position={[2.76, 1.78, 1.16]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane006_1.geometry}
					material={materials['Paper.001']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane006_2.geometry}
					material={materials['Book.001']}
				/>
			</group>
			<group position={[2.81, 1.81, 1.1]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane005_1.geometry}
					material={materials.Paper}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane005_2.geometry}
					material={materials.Book}
				/>
			</group>
			<group position={[2.8, 1.8, 1.21]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane007_1.geometry}
					material={materials['Paper.002']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane007_2.geometry}
					material={materials['Book.002']}
				/>
			</group>
			<group position={[2.82, 1.8, 1.27]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane008_1.geometry}
					material={materials['Paper.003']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane008_2.geometry}
					material={materials['Book.003']}
				/>
			</group>
			<group position={[2.78, 1.77, 1.4]} rotation={[-0.15, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane009_1.geometry}
					material={materials['Paper.004']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane009_2.geometry}
					material={materials['Book.004']}
				/>
			</group>
			<group position={[2.83, 1.82, 1.33]} rotation={[-0.15, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane010_1.geometry}
					material={materials['Paper.005']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane010_2.geometry}
					material={materials['Book.005']}
				/>
			</group>
			<group position={[2.81, 1.4, 0.45]} rotation={[-0.33, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane012_1.geometry}
					material={materials['Paper.006']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane012_2.geometry}
					material={materials['Book.006']}
				/>
			</group>
			<group position={[2.8, 1.39, 0.4]} rotation={[-0.33, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane017_1.geometry}
					material={materials['Paper.008']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane017_2.geometry}
					material={materials['Book.008']}
				/>
			</group>
			<group position={[2.82, 1.39, 0.34]} rotation={[-0.33, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane022_1.geometry}
					material={materials['Paper.009']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane022_2.geometry}
					material={materials['Book.009']}
				/>
			</group>
			<group position={[2.8, 1.41, 0.21]} rotation={[-0.33, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane023_1.geometry}
					material={materials['Paper.010']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane023_2.geometry}
					material={materials['Book.010']}
				/>
			</group>
			<group position={[2.76, 1.4, 0.28]} rotation={[-0.33, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane027_1.geometry}
					material={materials['Paper.011']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane027_2.geometry}
					material={materials['Book.011']}
				/>
			</group>
			<group position={[2.78, 1.35, 0.92]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane028_1.geometry}
					material={materials['Paper.012']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane028_2.geometry}
					material={materials['Book.012']}
				/>
			</group>
			<group position={[2.79, 1.36, 0.98]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane029_1.geometry}
					material={materials['Paper.013']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane029_2.geometry}
					material={materials['Book.013']}
				/>
			</group>
			<group position={[2.78, 1.38, 0.87]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane030_1.geometry}
					material={materials['Paper.014']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane030_2.geometry}
					material={materials['Book.014']}
				/>
			</group>
			<group position={[2.76, 1.41, 0.81]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane031_1.geometry}
					material={materials['Paper.015']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane031_2.geometry}
					material={materials['Book.015']}
				/>
			</group>
			<group position={[2.78, 1.37, 0.71]} rotation={[0.24, 0.04, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane032_1.geometry}
					material={materials['Paper.016']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane032_2.geometry}
					material={materials['Book.016']}
				/>
			</group>
			<group position={[2.8, 1.34, 0.76]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane033_1.geometry}
					material={materials['Paper.017']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane033_2.geometry}
					material={materials['Book.017']}
				/>
			</group>
			<group position={[2.78, 0.97, -0.16]} rotation={[0.22, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane034_1.geometry}
					material={materials['Paper.018']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane034_2.geometry}
					material={materials['Book.018']}
				/>
			</group>
			<group position={[2.78, 1, -0.21]} rotation={[0.22, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane035_1.geometry}
					material={materials['Paper.019']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane035_2.geometry}
					material={materials['Book.019']}
				/>
			</group>
			<group position={[2.72, 0.99, -0.1]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane036_1.geometry}
					material={materials['Paper.020']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane036_2.geometry}
					material={materials['Book.020']}
				/>
			</group>
			<group position={[2.78, 0.99, -0.04]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane037_1.geometry}
					material={materials['Paper.021']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane037_2.geometry}
					material={materials['Book.021']}
				/>
			</group>
			<group position={[2.76, 0.95, 0.07]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane038_1.geometry}
					material={materials['Paper.022']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane038_2.geometry}
					material={materials['Book.022']}
				/>
			</group>
			<group position={[2.77, 1, 0.02]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane039_1.geometry}
					material={materials['Paper.023']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane039_2.geometry}
					material={materials['Book.023']}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube105.geometry}
				material={materials.Drone}
				position={[-0.48, 1.41, -0.11]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle.geometry}
					material={materials['Rubber Black']}
					position={[0.09, 0, -0.07]}
				/>
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube112.geometry}
				material={materials['Material.013']}
				position={[6.24, 0.58, -0.83]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane021.geometry}
				material={materials.Leaves}
				position={[6.72, 0.36, -0.85]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane044.geometry}
				material={materials.Leaves}
				position={[6.32, 1.51, -0.66]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane045.geometry}
				material={materials.Leaves}
				position={[6.27, 1.61, -0.98]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane046.geometry}
				material={materials.Leaves}
				position={[6.12, 1.1, -0.67]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane047.geometry}
				material={materials.Leaves}
				position={[6.4, 1.04, -0.77]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane048.geometry}
				material={materials.Leaves}
				position={[6.21, 1.08, -0.99]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane049.geometry}
				material={materials.Leaves}
				position={[6.22, 0.94, -0.7]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane050.geometry}
				material={materials.Leaves}
				position={[6.13, 0.94, -0.87]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane051.geometry}
				material={materials.Leaves}
				position={[6.32, 0.94, -0.9]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane052.geometry}
				material={materials.Leaves}
				position={[6.41, 1.26, -0.97]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle002.geometry}
				material={materials.Soil}
				position={[6.24, 0.77, -0.83]}
				scale={[0.9, 1, 0.9]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube113.geometry}
				material={materials['Construction Sign.001']}
				position={[1.97, 0.84, 1.88]}
				rotation={[0.36, 0.75, -0.25]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane053.geometry}
				material={materials['Construction Sign']}
				position={[1.95, 0.98, 2.28]}
				rotation={[1.38, 0.18, -0.77]}
				scale={[0.31, 0.18, 0.14]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Text002.geometry}
				material={materials['Material.014']}
				position={[1.95, 1.04, 2.29]}
				rotation={[1.38, 0.18, -0.77]}
				scale={0.05}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Text003.geometry}
				material={materials['Material.014']}
				position={[1.97, 0.95, 2.3]}
				rotation={[1.38, 0.18, -0.77]}
				scale={0.05}
			/>
		</group>
	);
}

useGLTF.preload('/assets/room_alpha.gltf');
