// import React, { useLayoutEffect } from 'react';
// import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

// export const Room = ({ currentColor }) => {
// 	const { scene, nodes, materials } = useGLTF('/assets/room.gltf');
// 	return <primitive object={scene} />;
// };

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 room.gltf
*/

import React, { useState, useRef } from 'react';
import { ContentType } from '../sections/three-js-viewport';
import {
	useGLTF,
	useAnimations,
	AccumulativeShadows,
	RandomizedLight,
} from '@react-three/drei';

export function Model(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/assets/room.gltf');
	const { actions } = useAnimations(animations, group);

	// Functions
	function meshClicked(content: ContentType) {
		props.meshClicked(content);
	}

	return (
		<>
			{/* {showContent && <ContentPanel />} */}
			<group ref={group} {...props} dispose={null}>
				<group name='Scene'>
					<group
						name='Player'
						position={[1.21, 0.34, 1.68]}
						rotation={[Math.PI, -0.63, Math.PI]}
					>
						<primitive object={nodes.root} />
						<skinnedMesh
							name='Cat001'
							geometry={nodes.Cat001.geometry}
							material={materials.Mat_Gradient}
							skeleton={nodes.Cat001.skeleton}
						/>
					</group>
					{/* Guitar */}
					<group
						name='Node_24'
						position={[1.88, 2.02, -1.42]}
						rotation={[-Math.PI / 2, 0, -Math.PI]}
					>
						<group name='MachineHeads' position={[0, 0.22, -0.37]}>
							<mesh
								name='MH1'
								geometry={nodes.MH1.geometry}
								material={materials.Material_0}
								position={[-0.02, 0, 0.89]}
								rotation={[Math.PI, -1.31, Math.PI]}
							/>
							<mesh
								name='MH2'
								geometry={nodes.MH2.geometry}
								material={materials.Material_0}
								position={[-0.01, 0, 0.84]}
								rotation={[0, -0.44, 0]}
							/>
							<mesh
								name='MH3'
								geometry={nodes.MH3.geometry}
								material={materials.Material_0}
								position={[0, 0, 0.79]}
								rotation={[0, Math.PI / 8, 0]}
							/>
							<mesh
								name='MH4'
								geometry={nodes.MH4.geometry}
								material={materials.Material_0}
								position={[0.01, 0, 0.75]}
								rotation={[0, -0.7, 0]}
							/>
						</group>
						<group name='Strings' position={[0, 0.22, -0.37]}>
							<mesh
								name='cylinder'
								geometry={nodes.cylinder.geometry}
								material={materials.Material_0}
								position={[0.01, 0, 0.75]}
							/>
							<mesh
								name='String1'
								geometry={nodes.String1.geometry}
								material={materials.Material_0}
								position={[0, -0.22, 0.37]}
							/>
							<mesh
								name='String2'
								geometry={nodes.String2.geometry}
								material={materials.Material_0}
								position={[0, -0.22, 0.37]}
							/>
							<mesh
								name='String3'
								geometry={nodes.String3.geometry}
								material={materials.Material_0}
								position={[0, -0.22, 0.37]}
							/>
							<mesh
								name='String4'
								geometry={nodes.String4.geometry}
								material={materials.Material_0}
								position={[0, 0.01, 0.72]}
							/>
						</group>
						<mesh
							name='Body'
							geometry={nodes.Body.geometry}
							material={materials.Material_0}
						/>
						<mesh
							name='Bridge'
							geometry={nodes.Bridge.geometry}
							material={materials.Material_0}
						/>
						<mesh
							name='cube'
							geometry={nodes.cube.geometry}
							material={materials.Material_0}
						/>
						<mesh
							name='Frets'
							geometry={nodes.Frets.geometry}
							material={materials.Material_0}
						/>
						<mesh
							name='Input'
							geometry={nodes.Input.geometry}
							material={materials.Material_0}
						/>
						<mesh
							name='Neck&Head'
							geometry={nodes['Neck&Head'].geometry}
							material={materials.Material_0}
						/>
						<mesh
							name='Nobs1'
							geometry={nodes.Nobs1.geometry}
							material={materials.Material_0}
							position={[-0.1, 0, -0.42]}
						/>
						<mesh
							name='Nobs2'
							geometry={nodes.Nobs2.geometry}
							material={materials.Material_0}
							position={[-0.12, 0, -0.45]}
						/>
						<mesh
							name='Nobs3'
							geometry={nodes.Nobs3.geometry}
							material={materials.Material_0}
							position={[-0.14, 0, -0.48]}
						/>
						<mesh
							name='PickGuard'
							geometry={nodes.PickGuard.geometry}
							material={materials.Material_0}
						/>
						<mesh
							name='PickUps'
							geometry={nodes.PickUps.geometry}
							material={materials.Material_0}
						/>
						<mesh
							name='StrapPin1'
							geometry={nodes.StrapPin1.geometry}
							material={materials.Material_0}
							position={[-0.02, 0, -0.6]}
							rotation={[0, -0.13, 0]}
						/>
						<mesh
							name='StrapPin2'
							geometry={nodes.StrapPin2.geometry}
							material={materials.Material_0}
							position={[0.08, 0.14, -0.1]}
							rotation={[-Math.PI, Math.PI / 8, -Math.PI]}
						/>
					</group>
					<group
						name='d52651ad-2c5c-40ed-8bc0-32c215864f1d'
						position={[-0.65, 0.33, 1.55]}
						rotation={[Math.PI / 2, 0, -Math.PI / 3]}
					>
						<group name='Meshes' rotation={[0, 0, Math.PI / 6]}>
							<group
								name='Layer_1'
								rotation={[0, 0, Math.PI / 6]}
							>
								<mesh
									name='r0005'
									geometry={nodes.r0005.geometry}
									material={materials.Phong_FFFFFF}
									position={[0, 0, -4.51]}
									rotation={[-Math.PI / 2, Math.PI / 3, 0]}
								/>
								<mesh
									name='r0006'
									geometry={nodes.r0006.geometry}
									material={materials.Standard_68522A}
									position={[0, 0, -4.51]}
									rotation={[-Math.PI / 2, Math.PI / 3, 0]}
								/>
								<mesh
									name='s0014'
									geometry={nodes.s0014.geometry}
									material={materials.Phong_3D8344}
									position={[0.37, 0.05, -1.06]}
									rotation={[-0.55, 0.19, -1.31]}
								/>
								<mesh
									name='s0016'
									geometry={nodes.s0016.geometry}
									material={materials.Phong_3D8344}
									position={[0, 0, -0.35]}
									rotation={[0, 0, -0.33]}
								/>
								<mesh
									name='s0017'
									geometry={nodes.s0017.geometry}
									material={materials.Phong_3D8344}
									position={[0.14, -0.22, -0.53]}
									rotation={[-0.02, 0.29, -2.42]}
								/>
								<mesh
									name='s0018'
									geometry={nodes.s0018.geometry}
									material={materials.Phong_3D8344}
									position={[0.28, -0.01, -0.64]}
									rotation={[-0.15, 0.43, -1.08]}
								/>
								<mesh
									name='s0019'
									geometry={nodes.s0019.geometry}
									material={materials.Phong_3D8344}
									position={[0.19, 0.16, -0.77]}
									rotation={[-0.73, 0.07, -0.23]}
								/>
								<mesh
									name='s0020'
									geometry={nodes.s0020.geometry}
									material={materials.Phong_3D8344}
									position={[-0.08, 0.24, -0.83]}
									rotation={[-0.31, -0.44, 0.88]}
								/>
								<mesh
									name='s0021'
									geometry={nodes.s0021.geometry}
									material={materials.Phong_3D8344}
									position={[0.17, -0.11, -0.94]}
									rotation={[-0.46, 0.49, -1.71]}
								/>
								<mesh
									name='s0022'
									geometry={nodes.s0022.geometry}
									material={materials.Phong_3D8344}
									position={[0.04, 0.32, -1.02]}
									rotation={[-0.29, -0.16, 0.78]}
								/>
								<mesh
									name='s0023'
									geometry={nodes.s0023.geometry}
									material={materials.Phong_3D8344}
									position={[-0.11, -0.14, -0.54]}
									rotation={[0.43, -0.04, 2.9]}
								/>
								<mesh
									name='s0024'
									geometry={nodes.s0024.geometry}
									material={materials.Phong_3D8344}
									position={[-0.02, 0.22, -0.48]}
									rotation={[0.06, -0.34, 0.75]}
								/>
								<mesh
									name='s0025'
									geometry={nodes.s0025.geometry}
									material={materials.Phong_3D8344}
									position={[0.23, 0.08, -0.54]}
									rotation={[-0.42, 0.17, -0.62]}
								/>
								<mesh
									name='s0026'
									geometry={nodes.s0026.geometry}
									material={materials.Phong_3D8344}
									position={[-0.07, 0.15, -0.61]}
									rotation={[-0.09, -0.71, 1.18]}
								/>
								<mesh
									name='s0027'
									geometry={nodes.s0027.geometry}
									material={materials.Phong_3D8344}
									position={[-0.04, -0.14, -0.67]}
									rotation={[0.24, 0.25, 3.09]}
								/>
								<mesh
									name='s0028'
									geometry={nodes.s0028.geometry}
									material={materials.Phong_3D8344}
									position={[0.09, -0.14, -0.78]}
									rotation={[-0.2, 0.04, -2.22]}
								/>
								<mesh
									name='s0030'
									geometry={nodes.s0030.geometry}
									material={materials.Phong_3D8344}
									position={[-0.19, 0.01, -0.7]}
									rotation={[0.04, 0.01, 2.3]}
								/>
								<mesh
									name='s0033'
									geometry={nodes.s0033.geometry}
									material={materials.Standard_68522A}
									position={[0.03, -0.01, -0.4]}
									rotation={[-3.07, 0.22, -0.48]}
								/>
								<mesh
									name='s0034'
									geometry={nodes.s0034.geometry}
									material={materials.Standard_68522A}
									position={[0.12, -0.07, -0.4]}
									rotation={[-3.1, 0.14, -0.4]}
								/>
								<mesh
									name='s0035'
									geometry={nodes.s0035.geometry}
									material={materials.Standard_68522A}
									position={[0.03, -0.12, -0.4]}
									rotation={[-3.07, 0.15, -0.75]}
								/>
								<mesh
									name='s0036'
									geometry={nodes.s0036.geometry}
									material={materials.Standard_68522A}
									position={[-0.08, -0.02, -0.4]}
									rotation={[-3.06, 0.14, -0.85]}
								/>
								<mesh
									name='s0037'
									geometry={nodes.s0037.geometry}
									material={materials.Standard_68522A}
									position={[-0.04, 0.1, -0.4]}
									rotation={[3.11, 0.12, -0.48]}
								/>
								<mesh
									name='s0038'
									geometry={nodes.s0038.geometry}
									material={materials.Standard_68522A}
									position={[0.11, 0.09, -0.4]}
									rotation={[3.07, 0.09, -0.14]}
								/>
								<mesh
									name='s0039'
									geometry={nodes.s0039.geometry}
									material={materials.Standard_68522A}
									position={[0.1, 0, -0.4]}
									rotation={[3.13, 0.09, -0.28]}
								/>
								<mesh
									name='s0040'
									geometry={nodes.s0040.geometry}
									material={materials.Standard_8A773B}
									position={[0.06, -0.04, -0.39]}
									rotation={[3.09, 0.03, -0.27]}
								/>
								<mesh
									name='s0041'
									geometry={nodes.s0041.geometry}
									material={materials.Standard_8A773B}
									position={[-0.02, -0.13, -0.39]}
									rotation={[2.93, 0.27, -0.72]}
								/>
								<mesh
									name='s0042'
									geometry={nodes.s0042.geometry}
									material={materials.Standard_8A773B}
									position={[-0.03, -0.02, -0.39]}
									rotation={[3.02, 0.21, -0.6]}
								/>
								<mesh
									name='s0043'
									geometry={nodes.s0043.geometry}
									material={materials.Standard_8A773B}
									position={[-0.1, 0.07, -0.39]}
									rotation={[3.05, 0.15, -0.6]}
								/>
								<mesh
									name='s0044'
									geometry={nodes.s0044.geometry}
									material={materials.Standard_8A773B}
									position={[0.05, 0.12, -0.4]}
									rotation={[2.99, 0.04, -0.23]}
								/>
								<mesh
									name='s0045'
									geometry={nodes.s0045.geometry}
									material={materials.Standard_8A773B}
									position={[0.05, 0.04, -0.4]}
									rotation={[2.99, 0.12, -0.44]}
								/>
								<mesh
									name='s0046'
									geometry={nodes.s0046.geometry}
									material={materials.Standard_8A773B}
									position={[0.14, -0.01, -0.41]}
									rotation={[2.99, 0.13, -0.14]}
								/>
								<mesh
									name='s0047'
									geometry={nodes.s0047.geometry}
									material={materials.Phong_3D8344}
									position={[-0.19, 0.06, -0.88]}
									rotation={[0.12, -0.24, 2.01]}
								/>
								<mesh
									name='s0050'
									geometry={nodes.s0050.geometry}
									material={materials.Phong_3D8344}
									position={[-0.07, -0.07, -0.98]}
									rotation={[0.38, 0.19, 2.88]}
								/>
							</group>
						</group>
					</group>
					<mesh
						receiveShadow
						name='Plane'
						geometry={nodes.Plane.geometry}
						material={materials['Material.015']}
						position={[4.57, 0, 11.28]}
						rotation={[-Math.PI, 0, -Math.PI]}
						scale={1.04}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube106'
						geometry={nodes.Cube106.geometry}
						material={materials['Metal Black']}
						position={[1.9, 2.39, -1.25]}
					/>
					<group name='Plane015' position={[-0.1, -0.08, -0.14]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane005_1'
							geometry={nodes.Plane005_1.geometry}
							material={materials.Paper}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane005_2'
							geometry={nodes.Plane005_2.geometry}
							material={materials.Book}
						/>
					</group>
					<group name='Cube107' position={[2.75, 0.58, 1.27]}>
						<mesh
							castShadow
							receiveShadow
							name='Cube023_1'
							geometry={nodes.Cube023_1.geometry}
							material={materials['Bookshelf Inset']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Cube023_2'
							geometry={nodes.Cube023_2.geometry}
							material={materials.Nob}
						/>
					</group>
					<group name='Cube109' position={[2.75, 0.58, -0.09]}>
						<mesh
							castShadow
							receiveShadow
							name='Cube024_1'
							geometry={nodes.Cube024_1.geometry}
							material={materials['Bookshelf Inset']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Cube024_2'
							geometry={nodes.Cube024_2.geometry}
							material={materials.Nob}
						/>
					</group>
					<group name='Cube110' position={[2.75, 1, 0.81]}>
						<mesh
							castShadow
							receiveShadow
							name='Cube025_1'
							geometry={nodes.Cube025_1.geometry}
							material={materials['Bookshelf Inset']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Cube025_2'
							geometry={nodes.Cube025_2.geometry}
							material={materials.Nob}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Cube025_3'
							geometry={nodes.Cube025_3.geometry}
							material={materials['Chrome.005']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Cube025_4'
							geometry={nodes.Cube025_4.geometry}
							material={materials['Chrome.006']}
						/>
					</group>
					<group name='Cube111' position={[2.75, 1, 0.36]}>
						<mesh
							castShadow
							receiveShadow
							name='Cube027_1'
							geometry={nodes.Cube027_1.geometry}
							material={materials['Bookshelf Inset']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Cube027_2'
							geometry={nodes.Cube027_2.geometry}
							material={materials.Nob}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Cube027_3'
							geometry={nodes.Cube027_3.geometry}
							material={materials['Chrome.005']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Cube027_4'
							geometry={nodes.Cube027_4.geometry}
							material={materials['Chrome.006']}
						/>
					</group>
					<group name='Plane014' position={[-0.15, -0.08, -0.08]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane006_1'
							geometry={nodes.Plane006_1.geometry}
							material={materials['Paper.001']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane006_2'
							geometry={nodes.Plane006_2.geometry}
							material={materials['Book.001']}
						/>
					</group>
					<group name='Plane016' position={[-0.11, -0.08, -0.03]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane007_1'
							geometry={nodes.Plane007_1.geometry}
							material={materials['Paper.002']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane007_2'
							geometry={nodes.Plane007_2.geometry}
							material={materials['Book.002']}
						/>
					</group>
					<group name='Plane017' position={[-0.09, -0.08, 0.03]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane008_1'
							geometry={nodes.Plane008_1.geometry}
							material={materials['Paper.003']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane008_2'
							geometry={nodes.Plane008_2.geometry}
							material={materials['Book.003']}
						/>
					</group>
					<group
						name='Plane018'
						position={[-0.13, -0.23, 0.44]}
						rotation={[-0.15, 0, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Plane009_1'
							geometry={nodes.Plane009_1.geometry}
							material={materials['Paper.004']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane009_2'
							geometry={nodes.Plane009_2.geometry}
							material={materials['Book.004']}
						/>
					</group>
					<group
						name='Plane019'
						position={[-0.08, -0.23, 0.39]}
						rotation={[-0.15, 0, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Plane010_1'
							geometry={nodes.Plane010_1.geometry}
							material={materials['Paper.005']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane010_2'
							geometry={nodes.Plane010_2.geometry}
							material={materials['Book.005']}
						/>
					</group>
					<group
						name='Plane020'
						position={[-0.06, -0.06, 0.52]}
						rotation={[-0.33, 0, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Plane012_1'
							geometry={nodes.Plane012_1.geometry}
							material={materials['Paper.006']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane012_2'
							geometry={nodes.Plane012_2.geometry}
							material={materials['Book.006']}
						/>
					</group>
					<group
						name='Plane022'
						position={[-0.07, -0.04, 0.52]}
						rotation={[-0.33, 0, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Plane017_1'
							geometry={nodes.Plane017_1.geometry}
							material={materials['Paper.008']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane017_2'
							geometry={nodes.Plane017_2.geometry}
							material={materials['Book.008']}
						/>
					</group>
					<group
						name='Plane023'
						position={[-0.05, -0.02, 0.51]}
						rotation={[-0.33, 0, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Plane022_1'
							geometry={nodes.Plane022_1.geometry}
							material={materials['Paper.009']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane022_2'
							geometry={nodes.Plane022_2.geometry}
							material={materials['Book.009']}
						/>
					</group>
					<group
						name='Plane024'
						position={[-0.07, 0.01, 0.5]}
						rotation={[-0.33, 0, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Plane023_1'
							geometry={nodes.Plane023_1.geometry}
							material={materials['Paper.010']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane023_2'
							geometry={nodes.Plane023_2.geometry}
							material={materials['Book.010']}
						/>
					</group>
					<group
						name='Plane025'
						position={[-0.11, -0.01, 0.51]}
						rotation={[-0.33, 0, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Plane027_1'
							geometry={nodes.Plane027_1.geometry}
							material={materials['Paper.011']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane027_2'
							geometry={nodes.Plane027_2.geometry}
							material={materials['Book.011']}
						/>
					</group>
					<group name='Plane026' position={[-0.13, -0.49, -0.32]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane028_1'
							geometry={nodes.Plane028_1.geometry}
							material={materials['Paper.012']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane028_2'
							geometry={nodes.Plane028_2.geometry}
							material={materials['Book.012']}
						/>
					</group>
					<group name='Plane027' position={[-0.12, -0.49, -0.26]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane029_1'
							geometry={nodes.Plane029_1.geometry}
							material={materials['Paper.013']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane029_2'
							geometry={nodes.Plane029_2.geometry}
							material={materials['Book.013']}
						/>
					</group>
					<group name='Plane028' position={[-0.13, -0.49, -0.37]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane030_1'
							geometry={nodes.Plane030_1.geometry}
							material={materials['Paper.014']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane030_2'
							geometry={nodes.Plane030_2.geometry}
							material={materials['Book.014']}
						/>
					</group>
					<group name='Plane029' position={[-0.15, -0.49, -0.43]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane031_1'
							geometry={nodes.Plane031_1.geometry}
							material={materials['Paper.015']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane031_2'
							geometry={nodes.Plane031_2.geometry}
							material={materials['Book.015']}
						/>
					</group>
					<group
						name='Plane030'
						position={[-0.18, -0.17, -0.82]}
						rotation={[0.24, 0.04, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Plane032_1'
							geometry={nodes.Plane032_1.geometry}
							material={materials['Paper.016']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane032_2'
							geometry={nodes.Plane032_2.geometry}
							material={materials['Book.016']}
						/>
					</group>
					<group name='Plane031' position={[-0.11, -0.49, -0.49]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane033_1'
							geometry={nodes.Plane033_1.geometry}
							material={materials['Paper.017']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane033_2'
							geometry={nodes.Plane033_2.geometry}
							material={materials['Book.017']}
						/>
					</group>
					<group
						name='Plane032'
						position={[-0.13, -0.58, -1.78]}
						rotation={[0.22, 0, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Plane034_1'
							geometry={nodes.Plane034_1.geometry}
							material={materials['Paper.018']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane034_2'
							geometry={nodes.Plane034_2.geometry}
							material={materials['Book.018']}
						/>
					</group>
					<group
						name='Plane033'
						position={[-0.13, -0.58, -1.84]}
						rotation={[0.22, 0, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Plane035_1'
							geometry={nodes.Plane035_1.geometry}
							material={materials['Paper.019']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane035_2'
							geometry={nodes.Plane035_2.geometry}
							material={materials['Book.019']}
						/>
					</group>
					<group name='Plane034' position={[-0.19, -0.89, -1.34]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane036_1'
							geometry={nodes.Plane036_1.geometry}
							material={materials['Paper.020']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane036_2'
							geometry={nodes.Plane036_2.geometry}
							material={materials['Book.020']}
						/>
					</group>
					<group name='Plane035' position={[-0.13, -0.89, -1.28]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane037_1'
							geometry={nodes.Plane037_1.geometry}
							material={materials['Paper.021']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane037_2'
							geometry={nodes.Plane037_2.geometry}
							material={materials['Book.021']}
						/>
					</group>
					<group name='Plane036' position={[-0.15, -0.89, -1.17]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane038_1'
							geometry={nodes.Plane038_1.geometry}
							material={materials['Paper.022']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane038_2'
							geometry={nodes.Plane038_2.geometry}
							material={materials['Book.022']}
						/>
					</group>
					<group name='Plane037' position={[-0.14, -0.89, -1.22]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane039_1'
							geometry={nodes.Plane039_1.geometry}
							material={materials['Paper.023']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane039_2'
							geometry={nodes.Plane039_2.geometry}
							material={materials['Book.023']}
						/>
					</group>
					<group name='Plane038' position={[-0.14, -1.3, -0.77]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane040_1'
							geometry={nodes.Plane040_1.geometry}
							material={materials['Paper.024']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane040_2'
							geometry={nodes.Plane040_2.geometry}
							material={materials['Book.024']}
						/>
					</group>
					<group name='Plane039' position={[-0.11, -1.3, -0.71]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane041_1'
							geometry={nodes.Plane041_1.geometry}
							material={materials['Paper.025']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane041_2'
							geometry={nodes.Plane041_2.geometry}
							material={materials['Book.025']}
						/>
					</group>
					<group name='Plane040' position={[-0.1, -1.3, -0.83]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane042_1'
							geometry={nodes.Plane042_1.geometry}
							material={materials['Paper.026']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane042_2'
							geometry={nodes.Plane042_2.geometry}
							material={materials['Book.026']}
						/>
					</group>
					<group name='Plane041' position={[-0.12, -1.3, -0.88]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane043_1'
							geometry={nodes.Plane043_1.geometry}
							material={materials['Paper.027']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane043_2'
							geometry={nodes.Plane043_2.geometry}
							material={materials['Book.027']}
						/>
					</group>
					<group
						name='Plane042'
						position={[-0.12, -1.42, -0.82]}
						rotation={[-0.17, -0.04, -0.03]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Plane044_1'
							geometry={nodes.Plane044_1.geometry}
							material={materials['Paper.028']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane044_2'
							geometry={nodes.Plane044_2.geometry}
							material={materials['Book.028']}
						/>
					</group>
					<group name='Plane043' position={[-0.1, -1.3, -0.94]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane045_1'
							geometry={nodes.Plane045_1.geometry}
							material={materials['Paper.029']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane045_2'
							geometry={nodes.Plane045_2.geometry}
							material={materials['Book.029']}
						/>
					</group>
					<mesh
						castShadow
						receiveShadow
						name='Cube135'
						geometry={nodes.Cube135.geometry}
						material={materials['Shiny Metal.Window']}
						position={[0.76, 2.59, -1.57]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube115'
						geometry={nodes.Cube115.geometry}
						material={materials['Glass.007']}
						position={[0.8, 2.65, -1.64]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube116'
						geometry={nodes.Cube116.geometry}
						material={materials['Metal Black']}
						position={[0.8, 2.54, -1.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube117'
						geometry={nodes.Cube117.geometry}
						material={materials['Glass.007']}
						position={[0.8, 2.15, -1.58]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube141'
						geometry={nodes.Cube141.geometry}
						material={materials['Metal Black.003']}
						position={[0.8, 2.24, -1.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube103'
						geometry={nodes.Cube103.geometry}
						material={materials['Metal Black.001']}
						position={[0.8, 2.22, -1.64]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube104'
						geometry={nodes.Cube104.geometry}
						material={materials['Metal Black.004']}
						position={[0.8, 1.75, -1.58]}
					/>
					<mesh
						name='Floor'
						castShadow
						receiveShadow
						geometry={nodes.Floor.geometry}
						material={materials.Floor}
						position={[3.32, 0.16, 0.86]}
						rotation={[-Math.PI, 0, -Math.PI]}
					/>
					<mesh
						name='Right_Wall'
						castShadow
						receiveShadow
						geometry={nodes.Right_Wall.geometry}
						material={materials.Wall}
						position={[4.4, 1.8, -1.31]}
						rotation={[-Math.PI, 0, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Left_Wall'
						geometry={nodes.Left_Wall.geometry}
						material={materials.Wall}
						position={[-1.43, 1.8, 0.86]}
						rotation={[-Math.PI, 0, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Keyboard_Frame'
						geometry={nodes.Keyboard_Frame.geometry}
						material={materials['Keyboard Base']}
						position={[-0.07, 1.19, -0.11]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube015'
						geometry={nodes.Cube015.geometry}
						material={materials['Keyboard Base']}
						position={[-0.13, 1.23, 0.04]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube016'
						geometry={nodes.Cube016.geometry}
						material={nodes.Cube016.material}
						position={[-0.13, 1.23, 0]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube017'
						geometry={nodes.Cube017.geometry}
						material={nodes.Cube017.material}
						position={[-0.13, 1.23, -0.02]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube018'
						geometry={nodes.Cube018.geometry}
						material={nodes.Cube018.material}
						position={[-0.13, 1.23, -0.06]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube019'
						geometry={nodes.Cube019.geometry}
						material={nodes.Cube019.material}
						position={[-0.13, 1.23, -0.04]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube020'
						geometry={nodes.Cube020.geometry}
						material={materials['Keyboard Base']}
						position={[-0.13, 1.23, -0.12]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube021'
						geometry={nodes.Cube021.geometry}
						material={materials['Keyboard Base']}
						position={[-0.13, 1.23, -0.14]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube022'
						geometry={nodes.Cube022.geometry}
						material={materials['Keyboard Base']}
						position={[-0.13, 1.23, -0.1]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube023'
						geometry={nodes.Cube023.geometry}
						material={materials['Keyboard Base']}
						position={[-0.13, 1.23, -0.08]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube024'
						geometry={nodes.Cube024.geometry}
						material={nodes.Cube024.material}
						position={[-0.13, 1.23, -0.2]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube025'
						geometry={nodes.Cube025.geometry}
						material={nodes.Cube025.material}
						position={[-0.13, 1.23, -0.22]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube026'
						geometry={nodes.Cube026.geometry}
						material={nodes.Cube026.material}
						position={[-0.13, 1.23, -0.18]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube027'
						geometry={nodes.Cube027.geometry}
						material={nodes.Cube027.material}
						position={[-0.13, 1.23, -0.16]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube028'
						geometry={nodes.Cube028.geometry}
						material={materials['Keyboard Base']}
						position={[-0.13, 1.23, -0.24]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube029'
						geometry={nodes.Cube029.geometry}
						material={materials['Keyboard Base']}
						position={[-0.13, 1.23, -0.26]}
						rotation={[0, 0, -0.61]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube030'
						geometry={nodes.Cube030.geometry}
						material={nodes.Cube030.material}
						position={[-0.11, 1.22, 0.04]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube014'
						geometry={nodes.Cube014.geometry}
						material={nodes.Cube014.material}
						position={[-0.11, 1.22, 0]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube031'
						geometry={nodes.Cube031.geometry}
						material={nodes.Cube031.material}
						position={[-0.11, 1.22, 0.02]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube032'
						geometry={nodes.Cube032.geometry}
						material={nodes.Cube032.material}
						position={[-0.11, 1.22, -0.04]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube033'
						geometry={nodes.Cube033.geometry}
						material={nodes.Cube033.material}
						position={[-0.11, 1.22, -0.02]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube034'
						geometry={nodes.Cube034.geometry}
						material={nodes.Cube034.material}
						position={[-0.11, 1.22, -0.06]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube035'
						geometry={nodes.Cube035.geometry}
						material={nodes.Cube035.material}
						position={[-0.11, 1.22, -0.12]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube036'
						geometry={nodes.Cube036.geometry}
						material={nodes.Cube036.material}
						position={[-0.11, 1.22, -0.08]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube037'
						geometry={nodes.Cube037.geometry}
						material={nodes.Cube037.material}
						position={[-0.11, 1.22, -0.1]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube038'
						geometry={nodes.Cube038.geometry}
						material={nodes.Cube038.material}
						position={[-0.11, 1.22, -0.16]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube039'
						geometry={nodes.Cube039.geometry}
						material={nodes.Cube039.material}
						position={[-0.11, 1.22, -0.14]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube040'
						geometry={nodes.Cube040.geometry}
						material={nodes.Cube040.material}
						position={[-0.11, 1.22, -0.18]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube041'
						geometry={nodes.Cube041.geometry}
						material={nodes.Cube041.material}
						position={[-0.11, 1.22, -0.2]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube042'
						geometry={nodes.Cube042.geometry}
						material={materials['Keyboard Variant 1']}
						position={[-0.11, 1.22, -0.26]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube043'
						geometry={nodes.Cube043.geometry}
						material={materials['Keyboard Base']}
						position={[-0.11, 1.22, -0.23]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube044'
						geometry={nodes.Cube044.geometry}
						material={nodes.Cube044.material}
						position={[-0.08, 1.22, -0.24]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube045'
						geometry={nodes.Cube045.geometry}
						material={nodes.Cube045.material}
						position={[-0.08, 1.22, -0.21]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube046'
						geometry={nodes.Cube046.geometry}
						material={nodes.Cube046.material}
						position={[-0.08, 1.22, -0.17]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube047'
						geometry={nodes.Cube047.geometry}
						material={nodes.Cube047.material}
						position={[-0.08, 1.22, -0.19]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube048'
						geometry={nodes.Cube048.geometry}
						material={nodes.Cube048.material}
						position={[-0.08, 1.22, -0.13]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube049'
						geometry={nodes.Cube049.geometry}
						material={nodes.Cube049.material}
						position={[-0.08, 1.22, -0.11]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube050'
						geometry={nodes.Cube050.geometry}
						material={nodes.Cube050.material}
						position={[-0.08, 1.22, -0.15]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube051'
						geometry={nodes.Cube051.geometry}
						material={nodes.Cube051.material}
						position={[-0.08, 1.22, -0.09]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube052'
						geometry={nodes.Cube052.geometry}
						material={nodes.Cube052.material}
						position={[-0.08, 1.22, -0.05]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube053'
						geometry={nodes.Cube053.geometry}
						material={nodes.Cube053.material}
						position={[-0.08, 1.22, -0.07]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube054'
						geometry={nodes.Cube054.geometry}
						material={nodes.Cube054.material}
						position={[-0.08, 1.22, -0.01]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube055'
						geometry={nodes.Cube055.geometry}
						material={nodes.Cube055.material}
						position={[-0.08, 1.22, 0.01]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube056'
						geometry={nodes.Cube056.geometry}
						material={nodes.Cube056.material}
						position={[-0.08, 1.22, -0.03]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube057'
						geometry={nodes.Cube057.geometry}
						material={materials['Keyboard Base']}
						position={[-0.08, 1.22, 0.04]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube058'
						geometry={nodes.Cube058.geometry}
						material={materials['Keyboard Variant 1']}
						position={[-0.08, 1.22, -0.26]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube059'
						geometry={nodes.Cube059.geometry}
						material={materials['Keyboard Variant 1']}
						position={[-0.06, 1.22, -0.26]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube060'
						geometry={nodes.Cube060.geometry}
						material={materials['Keyboard Base']}
						position={[-0.06, 1.22, 0.03]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube061'
						geometry={nodes.Cube061.geometry}
						material={nodes.Cube061.material}
						position={[-0.06, 1.22, -0.04]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube062'
						geometry={nodes.Cube062.geometry}
						material={nodes.Cube062.material}
						position={[-0.06, 1.22, 0]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube063'
						geometry={nodes.Cube063.geometry}
						material={nodes.Cube063.material}
						position={[-0.06, 1.22, -0.02]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube064'
						geometry={nodes.Cube064.geometry}
						material={nodes.Cube064.material}
						position={[-0.06, 1.22, -0.08]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube065'
						geometry={nodes.Cube065.geometry}
						material={nodes.Cube065.material}
						position={[-0.06, 1.22, -0.06]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube066'
						geometry={nodes.Cube066.geometry}
						material={nodes.Cube066.material}
						position={[-0.06, 1.22, -0.09]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube067'
						geometry={nodes.Cube067.geometry}
						material={nodes.Cube067.material}
						position={[-0.06, 1.22, -0.15]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube068'
						geometry={nodes.Cube068.geometry}
						material={nodes.Cube068.material}
						position={[-0.06, 1.22, -0.11]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube069'
						geometry={nodes.Cube069.geometry}
						material={nodes.Cube069.material}
						position={[-0.06, 1.22, -0.13]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube070'
						geometry={nodes.Cube070.geometry}
						material={nodes.Cube070.material}
						position={[-0.06, 1.22, -0.19]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube071'
						geometry={nodes.Cube071.geometry}
						material={nodes.Cube071.material}
						position={[-0.06, 1.22, -0.17]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube073'
						geometry={nodes.Cube073.geometry}
						material={materials['Keyboard Base']}
						position={[-0.06, 1.22, -0.23]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube074'
						geometry={nodes.Cube074.geometry}
						material={materials['Keyboard Base']}
						position={[-0.04, 1.21, -0.21]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube075'
						geometry={nodes.Cube075.geometry}
						material={materials['Keyboard Base']}
						position={[-0.04, 1.21, -0.24]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube076'
						geometry={nodes.Cube076.geometry}
						material={nodes.Cube076.material}
						position={[-0.04, 1.21, -0.19]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube078'
						geometry={nodes.Cube078.geometry}
						material={nodes.Cube078.material}
						position={[-0.04, 1.21, -0.15]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube079'
						geometry={nodes.Cube079.geometry}
						material={nodes.Cube079.material}
						position={[-0.04, 1.21, -0.13]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube080'
						geometry={nodes.Cube080.geometry}
						material={materials['Keyboard Variant 2']}
						position={[-0.04, 1.21, -0.17]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube081'
						geometry={nodes.Cube081.geometry}
						material={nodes.Cube081.material}
						position={[-0.04, 1.21, -0.11]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube082'
						geometry={nodes.Cube082.geometry}
						material={nodes.Cube082.material}
						position={[-0.04, 1.21, -0.07]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube083'
						geometry={nodes.Cube083.geometry}
						material={nodes.Cube083.material}
						position={[-0.04, 1.21, -0.09]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube084'
						geometry={nodes.Cube084.geometry}
						material={nodes.Cube084.material}
						position={[-0.04, 1.21, -0.03]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube085'
						geometry={nodes.Cube085.geometry}
						material={nodes.Cube085.material}
						position={[-0.04, 1.21, -0.01]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube086'
						geometry={nodes.Cube086.geometry}
						material={nodes.Cube086.material}
						position={[-0.04, 1.21, -0.05]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube087'
						geometry={nodes.Cube087.geometry}
						material={materials['Keyboard Base']}
						position={[-0.04, 1.21, 0.03]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube088'
						geometry={nodes.Cube088.geometry}
						material={materials['Keyboard Variant 1']}
						position={[-0.04, 1.21, -0.26]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube091'
						geometry={nodes.Cube091.geometry}
						material={nodes.Cube091.material}
						position={[-0.02, 1.21, 0]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube092'
						geometry={nodes.Cube092.geometry}
						material={materials['Keyboard Base']}
						position={[-0.02, 1.21, 0.04]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube093'
						geometry={nodes.Cube093.geometry}
						material={nodes.Cube093.material}
						position={[-0.02, 1.21, 0.02]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube097'
						geometry={nodes.Cube097.geometry}
						material={materials['Keyboard Base']}
						position={[-0.02, 1.21, -0.2]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube098'
						geometry={nodes.Cube098.geometry}
						material={materials['Keyboard Base']}
						position={[-0.02, 1.21, -0.16]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube099'
						geometry={nodes.Cube099.geometry}
						material={materials['Keyboard Base']}
						position={[-0.02, 1.21, -0.18]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube100'
						geometry={nodes.Cube100.geometry}
						material={materials['Keyboard Base']}
						position={[-0.02, 1.21, -0.24]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube101'
						geometry={nodes.Cube101.geometry}
						material={materials['Keyboard Base']}
						position={[-0.02, 1.21, -0.22]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube102'
						geometry={nodes.Cube102.geometry}
						material={materials['Keyboard Base']}
						position={[-0.02, 1.21, -0.26]}
						rotation={[0, 0, -0.07]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube089'
						geometry={nodes.Cube089.geometry}
						material={materials['Keyboard Variant 1']}
						position={[-0.02, 1.21, -0.08]}
						rotation={[0, 0, -0.11]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Table_Top'
						geometry={nodes.Table_Top.geometry}
						material={materials['Wood Black']}
						position={[-0.7, 1.29, -0.09]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder003'
						geometry={nodes.Cylinder003.geometry}
						material={materials.Material}
						position={[-0.98, 0.54, 0.89]}
						rotation={[0.07, 0.07, -0.78]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder001'
						geometry={nodes.Cylinder001.geometry}
						material={materials['Material.001']}
						position={[-0.98, 0.54, -1.05]}
						rotation={[0.07, 0.07, -0.78]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube005'
						geometry={nodes.Cube005.geometry}
						material={materials['Wood Black']}
						position={[-0.13, 1.17, -0.08]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube012'
						geometry={nodes.Cube012.geometry}
						material={materials['Metal Black']}
						position={[-0.66, 1.21, 0.48]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube009'
						geometry={nodes.Cube009.geometry}
						material={materials['Metal Black']}
						position={[-0.66, 1.21, -0.65]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube118'
						geometry={nodes.Cube118.geometry}
						material={materials['Metal Black']}
						position={[-0.13, 1.17, 0.46]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube119'
						geometry={nodes.Cube119.geometry}
						material={materials['Metal Black']}
						position={[-0.13, 1.17, -0.64]}
					/>
					<group
						name='Cylinder01'
						position={[0.7, 0.51, -0.61]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Mesh'
							geometry={nodes.Mesh.geometry}
							material={materials.Matteplastic}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Mesh_1'
							geometry={nodes.Mesh_1.geometry}
							material={materials.BlackMetal}
						/>
					</group>
					<mesh
						castShadow
						receiveShadow
						name='Rectangle11'
						geometry={nodes.Rectangle11.geometry}
						material={materials.BlackMetal}
						position={[0.67, 0.88, -0.54]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Line01'
						geometry={nodes.Line01.geometry}
						material={materials.BlackMetal}
						position={[0.71, 0.8, -0.65]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder03'
						geometry={nodes.Cylinder03.geometry}
						material={materials.Matteplastic}
						position={[0.67, 0.79, -0.52]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Line02'
						geometry={nodes.Line02.geometry}
						material={materials.BlackMetal}
						position={[0.45, 0.79, -0.75]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Circle01'
						geometry={nodes.Circle01.geometry}
						material={materials.Matteplastic}
						position={[0.4, 0.8, -0.81]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder07'
						geometry={nodes.Cylinder07.geometry}
						material={materials.BlackMetal}
						position={[0.91, 0.83, -0.5]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder08'
						geometry={nodes.Cylinder08.geometry}
						material={materials.BlackMetal}
						position={[0.88, 0.84, -0.42]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder09'
						geometry={nodes.Cylinder09.geometry}
						material={materials.BlackMetal}
						position={[0.95, 0.85, -0.4]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder10'
						geometry={nodes.Cylinder10.geometry}
						material={materials.BlackMetal}
						position={[0.97, 0.84, -0.48]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder11'
						geometry={nodes.Cylinder11.geometry}
						material={materials.BlackMetal}
						position={[0.4, 0.84, -0.67]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder12'
						geometry={nodes.Cylinder12.geometry}
						material={materials.BlackMetal}
						position={[0.46, 0.83, -0.65]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder13'
						geometry={nodes.Cylinder13.geometry}
						material={materials.BlackMetal}
						position={[0.37, 0.85, -0.6]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder14'
						geometry={nodes.Cylinder14.geometry}
						material={materials.BlackMetal}
						position={[0.44, 0.83, -0.58]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Line04'
						geometry={nodes.Line04.geometry}
						material={materials.Matteplastic}
						position={[0.33, 1.11, -0.69]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder15'
						geometry={nodes.Cylinder15.geometry}
						material={materials.BlackMetal}
						position={[0.34, 0.92, -0.71]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder16'
						geometry={nodes.Cylinder16.geometry}
						material={materials.BlackMetal}
						position={[0.31, 0.92, -0.62]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Line05'
						geometry={nodes.Line05.geometry}
						material={materials.Matteplastic}
						position={[1.03, 1.11, -0.45]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder17'
						geometry={nodes.Cylinder17.geometry}
						material={materials.BlackMetal}
						position={[1.01, 0.92, -0.38]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder18'
						geometry={nodes.Cylinder18.geometry}
						material={materials.BlackMetal}
						position={[1.04, 0.92, -0.47]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Box01'
						geometry={nodes.Box01.geometry}
						material={materials.Lether}
						position={[0.57, 0.93, -0.25]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					/>
					<group
						name='Box02'
						position={[1.14, 1.2, -0.86]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Mesh022'
							geometry={nodes.Mesh022.geometry}
							material={materials.Lether}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Mesh022_1'
							geometry={nodes.Mesh022_1.geometry}
							material={materials.Chairback}
						/>
					</group>
					<mesh
						castShadow
						receiveShadow
						name='Rectangle02'
						geometry={nodes.Rectangle02.geometry}
						material={materials.Chrome}
						position={[0.7, 0.48, -0.61]}
						rotation={[-Math.PI, -1.24, -Math.PI]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Cylinder04'
							geometry={nodes.Cylinder04.geometry}
							material={materials.Matteplastic}
							position={[-0.13, -0.05, -0.37]}
						>
							<mesh
								castShadow
								receiveShadow
								name='Cylinder02'
								geometry={nodes.Cylinder02.geometry}
								material={materials.Matteplastic}
								position={[-0.02, -0.06, 0]}
							/>
						</mesh>
						<mesh
							castShadow
							receiveShadow
							name='Cylinder20'
							geometry={nodes.Cylinder20.geometry}
							material={materials.Matteplastic}
							position={[0.31, -0.05, -0.23]}
						>
							<mesh
								castShadow
								receiveShadow
								name='Cylinder19'
								geometry={nodes.Cylinder19.geometry}
								material={materials.Matteplastic}
								position={[-0.01, -0.06, -0.02]}
							/>
						</mesh>
						<mesh
							castShadow
							receiveShadow
							name='Cylinder21'
							geometry={nodes.Cylinder21.geometry}
							material={materials.Matteplastic}
							position={[0.32, -0.05, 0.22]}
						>
							<mesh
								castShadow
								receiveShadow
								name='Cylinder22'
								geometry={nodes.Cylinder22.geometry}
								material={materials.Matteplastic}
								position={[0.01, -0.06, -0.02]}
							/>
						</mesh>
						<mesh
							castShadow
							receiveShadow
							name='Cylinder23'
							geometry={nodes.Cylinder23.geometry}
							material={materials.Matteplastic}
							position={[-0.11, -0.05, 0.37]}
						>
							<mesh
								castShadow
								receiveShadow
								name='Cylinder24'
								geometry={nodes.Cylinder24.geometry}
								material={materials.Matteplastic}
								position={[0.02, -0.06, 0]}
							/>
						</mesh>
						<mesh
							castShadow
							receiveShadow
							name='Cylinder26'
							geometry={nodes.Cylinder26.geometry}
							material={materials.Matteplastic}
							position={[-0.39, -0.05, 0.01]}
						>
							<mesh
								castShadow
								receiveShadow
								name='Cylinder25'
								geometry={nodes.Cylinder25.geometry}
								material={materials.Matteplastic}
								position={[-0.01, -0.06, -0.02]}
							/>
						</mesh>
					</mesh>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder'
						geometry={nodes.Cylinder.geometry}
						material={materials['Table Lamp']}
						position={[-0.41, 1.35, 0.98]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder018'
						geometry={nodes.Cylinder018.geometry}
						material={materials['Table Lamp']}
						position={[-0.41, 1.98, 0.76]}
						rotation={[0, 0, -Math.PI / 2]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Bedframe'
						geometry={nodes.Bedframe.geometry}
						material={materials['Wood Black']}
						position={[4.53, 0.42, 0.18]}
						rotation={[0, 1.57, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane007'
						geometry={nodes.Plane007.geometry}
						material={materials['Material.010']}
						position={[4.53, 1.25, 0.42]}
						rotation={[-Math.PI, -0.76, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane006'
						geometry={nodes.Plane006.geometry}
						material={materials['Material.010']}
						position={[4.53, 0.61, 0.16]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane003'
						geometry={nodes.Plane003.geometry}
						material={materials['Material.010']}
						position={[4.47, 1.18, -0.62]}
						rotation={[-0.06, -0.26, 0.62]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane005'
						geometry={nodes.Plane005.geometry}
						material={materials['Material.010']}
						position={[4.54, 1.18, -0.4]}
						rotation={[0.05, -0.98, -0.24]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube001'
						geometry={nodes.Cube001.geometry}
						material={materials['Wood Black']}
						position={[4.53, 0.75, -1.21]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube002'
						geometry={nodes.Cube002.geometry}
						material={materials['Wood Black']}
						position={[4.53, 1.01, -1.21]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube003'
						geometry={nodes.Cube003.geometry}
						material={materials['Wood Black']}
						position={[4.53, 1.28, -1.21]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube004'
						geometry={nodes.Cube004.geometry}
						material={materials['Wood Black']}
						position={[4.53, 1.55, -1.21]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane004'
						geometry={nodes.Plane004.geometry}
						material={materials['Metal Black']}
						position={[3.31, 0.73, -0.97]}
						rotation={[0, 1.57, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane011'
						geometry={nodes.Plane011.geometry}
						material={materials['Metal Black']}
						position={[5.72, 0.73, -0.97]}
						rotation={[0, 1.57, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane012'
						geometry={nodes.Plane012.geometry}
						material={materials['Metal Black']}
						position={[3.32, 1.31, -0.97]}
						rotation={[0, 1.57, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane013'
						geometry={nodes.Plane013.geometry}
						material={materials['Metal Black']}
						position={[5.73, 1.31, -0.97]}
						rotation={[0, 1.57, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube121'
						geometry={nodes.Cube121.geometry}
						material={materials['Metal Black']}
						position={[-0.9, 1.35, 0.85]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube122'
						geometry={nodes.Cube122.geometry}
						material={materials['Rubber Black']}
						position={[-0.9, 1.43, 0.68]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube123'
						geometry={nodes.Cube123.geometry}
						material={materials['Metal Black']}
						position={[-0.91, 1.6, 0.85]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube124'
						geometry={nodes.Cube124.geometry}
						material={materials['Metal Black']}
						position={[-0.91, 1.6, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube125'
						geometry={nodes.Cube125.geometry}
						material={materials['Metal Black']}
						position={[-0.9, 1.35, 0.52]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube126'
						geometry={nodes.Cube126.geometry}
						material={materials['Metal Black']}
						position={[-0.82, 1.39, 0.69]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube127'
						geometry={nodes.Cube127.geometry}
						material={materials['Metal Black']}
						position={[-0.88, 1.52, 0.68]}
						rotation={[Math.PI / 2, 0, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube128'
						geometry={nodes.Cube128.geometry}
						material={materials['Metal Black']}
						position={[-0.91, 1.86, 0.68]}
						rotation={[Math.PI / 2, 0, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube129'
						geometry={nodes.Cube129.geometry}
						material={materials['Metal Black']}
						position={[-0.91, 1.92, 0.76]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder007'
						geometry={nodes.Cylinder007.geometry}
						material={materials['Rubber Black']}
						position={[-0.96, 1.97, 0.76]}
						rotation={[0, 0, -Math.PI / 2]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder008'
						geometry={nodes.Cylinder008.geometry}
						material={materials['Rubber Black']}
						position={[-0.93, 1.97, 0.76]}
						rotation={[0, 0, -Math.PI / 2]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder009'
						geometry={nodes.Cylinder009.geometry}
						material={materials['Rubber Black']}
						position={[-0.98, 1.97, 0.76]}
						rotation={[0, 0, -Math.PI / 2]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder010'
						geometry={nodes.Cylinder010.geometry}
						material={materials['Rubber Black']}
						position={[-1.02, 1.97, 0.76]}
						rotation={[0, 0, -Math.PI / 2]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube130'
						geometry={nodes.Cube130.geometry}
						material={materials['Metal Black']}
						position={[-0.72, 1.36, 0.51]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube132'
						geometry={nodes.Cube132.geometry}
						material={materials['Glass.001']}
						position={[-0.75, 1.4, 0.51]}
						rotation={[0, 0, 0.96]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder011'
						geometry={nodes.Cylinder011.geometry}
						material={materials['Metal Black']}
						position={[-0.72, 1.39, 0.49]}
						rotation={[0, 0, -Math.PI / 5]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube006'
						geometry={nodes.Cube006.geometry}
						material={materials['Metal Black']}
						position={[-0.83, 1.58, -1.04]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube120'
						geometry={nodes.Cube120.geometry}
						material={materials['Glass.007']}
						position={[-0.83, 1.64, -0.8]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube'
						geometry={nodes.Cube.geometry}
						material={materials['Rubber Black']}
						position={[-0.91, 1.57, -0.93]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube072'
						geometry={nodes.Cube072.geometry}
						material={materials['Material.002']}
						position={[-0.94, 1.55, -0.85]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube077'
						geometry={nodes.Cube077.geometry}
						material={materials.Mat_Gradient}
						position={[-0.94, 1.55, -0.85]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder002'
						geometry={nodes.Cylinder002.geometry}
						material={materials['Plastic Light']}
						position={[-0.66, 1.84, -1.01]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder004'
						geometry={nodes.Cylinder004.geometry}
						material={materials['Rubber Black']}
						position={[-0.93, 1.7, -1.01]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder005'
						geometry={nodes.Cylinder005.geometry}
						material={materials['Material.003']}
						position={[-0.93, 1.7, -0.99]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder006'
						geometry={nodes.Cylinder006.geometry}
						material={materials['Material.004']}
						position={[-0.93, 1.7, -0.99]}
						rotation={[-Math.PI / 2, 0, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder012'
						geometry={nodes.Cylinder012.geometry}
						material={materials['Table Lamp']}
						position={[-0.41, 1.3, 0.98]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder013'
						geometry={nodes.Cylinder013.geometry}
						material={materials['Table Lamp']}
						position={[-0.41, 1.65, 0.88]}
						rotation={[-0.34, 0, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder014'
						geometry={nodes.Cylinder014.geometry}
						material={materials['Table Lamp']}
						position={[-0.41, 2.07, 0.5]}
						rotation={[-1.27, 0, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube131'
						geometry={nodes.Cube131.geometry}
						material={materials['Table Lamp']}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube133'
						geometry={nodes.Cube133.geometry}
						material={materials['Material.007']}
						position={[-0.41, 2.16, -0.05]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder015'
						geometry={nodes.Cylinder015.geometry}
						material={materials['Table Lamp']}
						position={[-0.41, 2.16, 0.25]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder019'
						geometry={nodes.Cylinder019.geometry}
						material={materials['Metal Black.007']}
						position={[-0.68, 1.37, -0.64]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder020'
						geometry={nodes.Cylinder020.geometry}
						material={materials['Table Lamp']}
						position={[-0.68, 1.37, -0.64]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube008'
						geometry={nodes.Cube008.geometry}
						material={
							false
								? materials['Material.009']
								: new THREE.MeshLambertMaterial({
										color: '#F00',
										emissive: '#0FF',
								  })
						}
						position={[0.08, 0, 0]}
						onPointerEnter={(self) => {
							document.body.style.cursor = 'pointer';
						}}
						onPointerLeave={() => {
							document.body.style.cursor = 'auto';
						}}
						onClick={() => meshClicked(ContentType.Projects)}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube134'
						geometry={nodes.Cube134.geometry}
						material={materials['Metal Black']}
						position={[-0.89, 1.65, -0.09]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube108'
						geometry={nodes.Cube108.geometry}
						material={materials['Rubber Black']}
						position={[0.08, 0, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube010'
						geometry={nodes.Cube010.geometry}
						material={materials['Rubber Black']}
						position={[-1, 1.5, -0.07]}
						rotation={[Math.PI, 0, -2.88]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube011'
						geometry={nodes.Cube011.geometry}
						material={materials['Rubber Black']}
						position={[-1.01, 1.34, -0.09]}
						rotation={[-Math.PI, 0, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane008'
						geometry={nodes.Plane008.geometry}
						material={materials['Metal Black Phone']}
						position={[-0.4, 1.33, -0.49]}
						rotation={[0, -0.41, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane010'
						geometry={nodes.Plane010.geometry}
						material={materials['Material.008']}
						position={[-0.4, 1.33, -0.49]}
						rotation={[0, -0.41, 0]}
					/>
					<group name='Sphere001' position={[-0.83, 1.38, -0.09]}>
						<mesh
							castShadow
							receiveShadow
							name='Sphere004'
							geometry={nodes.Sphere004.geometry}
							material={materials['Material.008']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Sphere004_1'
							geometry={nodes.Sphere004_1.geometry}
							material={materials['Rubber Black']}
						/>
					</group>
					<group name='Plane009' position={[-0.89, 0.37, 2.37]}>
						<mesh
							castShadow
							receiveShadow
							name='Plane018_1'
							geometry={nodes.Plane018_1.geometry}
							material={materials['Glass.003']}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Plane018_2'
							geometry={nodes.Plane018_2.geometry}
							material={materials['Metal Black']}
						/>
					</group>
					<mesh
						castShadow
						receiveShadow
						name='Cube007'
						geometry={nodes.Cube007.geometry}
						material={materials['Rubber Black']}
						position={[-0.52, 1.33, -0.09]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube096'
						geometry={nodes.Cube096.geometry}
						material={materials['Material.019']}
						position={[-1.24, 2.24, 1.71]}
						onPointerEnter={() => {
							document.body.style.cursor = 'pointer';
						}}
						onPointerLeave={() => {
							document.body.style.cursor = 'auto';
						}}
						onClick={() => meshClicked(ContentType.Resume)}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane001'
						geometry={nodes.Plane001.geometry}
						material={materials['Wood Black']}
						position={[-1.27, 2.24, 1.71]}
						rotation={[0, 0, -Math.PI / 2]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube090'
						geometry={nodes.Cube090.geometry}
						material={materials['Material.019']}
						position={[-1.24, 1.86, 2.49]}
						onPointerEnter={() => {
							document.body.style.cursor = 'pointer';
						}}
						onPointerLeave={() => {
							document.body.style.cursor = 'auto';
						}}
						onClick={() => meshClicked(ContentType.Resume)}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane002'
						geometry={nodes.Plane002.geometry}
						material={materials['Wood Black']}
						position={[-1.27, 1.86, 2.49]}
						rotation={[0, 0, -Math.PI / 2]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube094'
						geometry={nodes.Cube094.geometry}
						material={materials['Bed Painting']}
						position={[4.53, 2.46, -1.25]}
						rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube095'
						geometry={nodes.Cube095.geometry}
						material={materials['Wood Black']}
						position={[4.53, 2.46, -1.23]}
						rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Text'
						geometry={nodes.Text.geometry}
						material={materials['Material.005']}
						position={[-0.57, 4.18, 3.73]}
						rotation={[1.24, 0.35, -0.78]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Text001'
						geometry={nodes.Text001.geometry}
						material={materials['Material.006']}
						position={[-0.93, 2.95, 0.87]}
						rotation={[1.24, 0.35, -0.78]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Sphere005'
						geometry={nodes.Sphere005.geometry}
						material={materials['Glass Bulb.001']}
						position={[2.93, 2.06, -0.81]}
						rotation={[-2.3, 0.85, 2.74]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Sphere006'
						geometry={nodes.Sphere006.geometry}
						material={materials['Glass Bulb.001']}
						position={[2.93, 2.06, -0.81]}
						rotation={[-2.3, 0.85, 2.74]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Sphere007'
						geometry={nodes.Sphere007.geometry}
						material={materials['Plastic Light Cover.001']}
						position={[3.01, 1.97, -0.78]}
						rotation={[0.84, -0.85, -0.24]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder016'
						geometry={nodes.Cylinder016.geometry}
						material={nodes.Cylinder016.material}
						position={[2.83, 0.37, -0.83]}
						rotation={[-Math.PI, 1.38, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cylinder017'
						geometry={nodes.Cylinder017.geometry}
						material={nodes.Cylinder017.material}
						position={[2.83, 1.5, -0.83]}
						rotation={[-Math.PI, 1.38, -Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Sphere002'
						geometry={nodes.Sphere002.geometry}
						material={materials['Plastic Light Cover.002']}
						position={[2.91, 2.42, -0.66]}
						rotation={[1.32, -1.04, 0.34]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Sphere003'
						geometry={nodes.Sphere003.geometry}
						material={materials['Glass Bulb.002']}
						position={[2.85, 2.51, -0.72]}
						rotation={[-1.82, 1.04, 2.16]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube148'
						geometry={nodes.Cube148.geometry}
						material={materials['Material.012']}
						position={[4.53, 0.35, 0.46]}
						rotation={[0, 1.57, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube013'
						geometry={nodes.Cube013.geometry}
						material={materials['Wood Black']}
						position={[-0.07, 0, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Icosphere'
						geometry={nodes.Icosphere.geometry}
						material={materials.Firefly}
						position={[-0.09, 0.01, -0.07]}
						rotation={[-2.35, -1.49, -2.38]}
					/>
					<group
						name='NurbsPath'
						position={[0.6, 1.34, -1.97]}
						rotation={[-Math.PI, 0, -Math.PI]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Mesh_2'
							geometry={nodes.Mesh_2.geometry}
							material={nodes.Mesh_2.material}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Mesh_3'
							geometry={nodes.Mesh_3.geometry}
							material={nodes.Mesh_3.material}
						/>
					</group>
					<group
						name='NurbsPath001'
						position={[0.85, 0.28, 1.2]}
						rotation={[-Math.PI, 0, -Math.PI]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Mesh_2'
							geometry={nodes.Mesh_2.geometry}
							material={nodes.Mesh_2.material}
						/>
						<mesh
							castShadow
							receiveShadow
							name='Mesh_3'
							geometry={nodes.Mesh_3.geometry}
							material={nodes.Mesh_3.material}
						/>
					</group>
					<mesh
						castShadow
						receiveShadow
						name='Icosphere001'
						geometry={nodes.Icosphere001.geometry}
						material={materials['Firefly.001']}
						position={[-0.05, 0.07, 0.09]}
						rotation={[3.07, 0, Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Cube105'
						geometry={nodes.Cube105.geometry}
						material={materials.Drone}
						position={[-0.48, 1.38, -0.11]}
					>
						<mesh
							castShadow
							receiveShadow
							name='Circle'
							geometry={nodes.Circle.geometry}
							material={materials['Rubber Black']}
							position={[0.1, 0, -0.07]}
						/>
					</mesh>
					<mesh
						castShadow
						receiveShadow
						name='Cube112'
						geometry={nodes.Cube112.geometry}
						material={materials['Material.013']}
						position={[6.24, 0.33, -0.83]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane021'
						geometry={nodes.Plane021.geometry}
						material={materials.Leaves}
						position={[6.24, 0.33, -0.83]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane044'
						geometry={nodes.Plane044.geometry}
						material={materials.Leaves}
						position={[6.24, 0.33, -0.83]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane045'
						geometry={nodes.Plane045.geometry}
						material={materials.Leaves}
						position={[6.24, 0.33, -0.83]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane046'
						geometry={nodes.Plane046.geometry}
						material={materials.Leaves}
						position={[6.24, 0.33, -0.83]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane047'
						geometry={nodes.Plane047.geometry}
						material={materials.Leaves}
						position={[6.24, 0.33, -0.83]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane048'
						geometry={nodes.Plane048.geometry}
						material={materials.Leaves}
						position={[6.24, 0.33, -0.83]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane049'
						geometry={nodes.Plane049.geometry}
						material={materials.Leaves}
						position={[6.24, 0.33, -0.83]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane050'
						geometry={nodes.Plane050.geometry}
						material={materials.Leaves}
						position={[6.24, 0.33, -0.83]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane051'
						geometry={nodes.Plane051.geometry}
						material={materials.Leaves}
						position={[6.24, 0.33, -0.83]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Plane052'
						geometry={nodes.Plane052.geometry}
						material={materials.Leaves}
						position={[6.24, 0.33, -0.83]}
					/>
					<mesh
						castShadow
						receiveShadow
						name='Circle002'
						geometry={nodes.Circle002.geometry}
						material={materials.Soil}
						position={[6.24, 0.33, -0.83]}
					/>
				</group>
			</group>
		</>
	);
}

useGLTF.preload('/assets/room.gltf');
